### ISSUE TITLE
Email notification broken: from address is hard coded (bexis2@uni-jena.de)

### ISSUE THREAD

**Issue by jbiermann** [BEXIS2/Core#10]
My BEXIS system can't send emails because the email server refuses the mail because the sender address is not allowed. I have seen that the from address is hard coded:
EmailService.cs
var from = new MailAddress("bexis2@uni-jena.de");

This is very bad. Please use a setting like Email_Sender for this (which you can put into credentials config or web.cfg).

**Comment by sventhiel** [comment]
There are no "hard coded" positions of that constructor inside the whole application anymore. 

Now, the system email address is read from a config file.
