### ISSUE TITLE
Wiki page for E2E tests recordings for Data Manager

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1010]
- use playwright VSC extension (how to set it up,...)
- how to record (structure, ..) simple "page loads and shows any content (not error page) tests"
- how to adjust the "last line" if necessary
- create a base settings file (check all browsers, ...)
- 
https://playwright.dev/docs/getting-started-vscode

consider also : https://playwright.dev/docs/test-snapshots ?

**Comment by DavidBlaa** [comment]
cool
