### ISSUE TITLE
download notification mail on media preview

### ISSUE THREAD

**Issue by sventhiel** [BEXIS2/Core#1023]
### Is there an existing issue for this?

- [X] I searched for a similar issue and didn't find a suitable one.

### What is going wrong?

Similar issue was already solved for images (#767). But there are more media types that need to be considered.

### Which task(s) is/are related to this issue?

- [x] #767
- [x] #1024

**Comment by geofranzi** [comment]
can we close?

**Comment by sventhiel** [comment]
Yeah.
