### ISSUE TITLE
Version API: Add

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1028]
To retrieve the current version for info and maintenance reasons automatically, we need a Version API. The API should return the following information:

- [ ] Site
- [ ] Database
- [ ] Workspace

**Comment by sventhiel** [comment]
Hej,
sorry for the lack of communication, but I introduced those apis already.

Return all versions at once: {base_url}/api/versions

Furthermore, for every single part of BEXIS2, use the following:

site -> {base_url}/api/versions/site
workspace -> {base_url}/api/versions/workspace
db -> {base_url}/api/versions/database
