### ISSUE TITLE
Documents view for endusers

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#103]
**Is your feature request related to a problem? Please describe.**
There should be a view where user can see the general documents for the system.
Currently a document Management is availbale but this ist not for the user but only for the managers.

**Describe the solution you'd like**
There is a xml document that descripes categories, folders and files.

the soultion can lock like this.
![image](https://user-images.githubusercontent.com/19665289/43185913-87ab9f66-8fed-11e8-9d7d-3e5f28969344.png)

**Comment by matparsa** [comment]
The required page is available with this address  /SAM/Files/FileList

**Comment by DavidBlaa** [comment]
cant reach the page 

![image](https://user-images.githubusercontent.com/19665289/44706767-f82e2e00-aaa2-11e8-988a-90838e7a0509.png)

How the user should reach the page. Where is the entry point?

**Comment by matparsa** [comment]
I added it to the menu
![image](https://user-images.githubusercontent.com/14373134/44942971-c5937680-adbd-11e8-9b31-8d62d3ecc5f4.png)

**Comment by navabpourn** [comment]
Please see the issue #165

**Comment by navabpourn** [comment]
Dear @DavidBlaa,
Everything works fine in both ports 2001 and 2002.
Thanks :)

**Comment by DavidBlaa** [comment]
thx
