### ISSUE TITLE
DCM - Attachments 500 Error (not logged in)

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#104]
- not logged in 
- view dataset
- click on Attachments

![image](https://user-images.githubusercontent.com/15946467/43255381-f6c4b234-90c9-11e8-865f-23c657a67fd7.png)

**Comment by matparsa** [comment]
I couldn't reproduce the issue. Maybe it was before the pushing my last changes to the release. This screenshot is for my current code which I am not logged in and the attachments tab is disabled for me.
![image](https://user-images.githubusercontent.com/14373134/43708161-1efd5d2a-996a-11e8-8bbc-ce054b41a4ae.png)

**Comment by navabpourn** [comment]
I am able to produce it in RC2 :(

**Comment by DavidBlaa** [comment]
now you can try it again

**Comment by matparsa** [comment]
it should be fixed now.

**Comment by DavidBlaa** [comment]
![image](https://user-images.githubusercontent.com/19665289/44456881-1064ff80-a602-11e8-86c1-2cc7a1a193b0.png)

**Comment by matparsa** [comment]
in RC4 it's correct.
![image](https://user-images.githubusercontent.com/14373134/44942592-7cd7bf80-adb5-11e8-9a62-eb883ab3831c.png)

**Comment by romangerlach** [comment]
solved
