### ISSUE TITLE
WebShell UI: Download not allowed info

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#105]
- explain what to do now (e.g. log in, request permission ..)

![image](https://user-images.githubusercontent.com/15946467/43255718-ed7e69f8-90ca-11e8-993c-545e17e9241e.png)

**Comment by DavidBlaa** [comment]
the permissions are checked before the function and exact details about what happens in a function are not clear at the time.

i agree with you that something needs to be improved.  but i will set it to the next release
