### ISSUE TITLE
Relationships title has a : 

### ISSUE THREAD

**Issue by EleonoraPetzold** [BEXIS2/Core#1057]
### Is there an existing issue for this?

- [X] I searched for a similar issue and didn't find a suitable one.

### What is going wrong?

Relationships title has a : in name.

**Comment by aostrow** [comment]
Attention: there was also a blank character ( ) after the colon (:) stored in the database. Is this also removed now? Tested?

**Comment by EleonoraPetzold** [comment]
Oh yes, sorry, the blank char is still there. I will fix it!
