### ISSUE TITLE
DDM - Non-public datasets are shown after log out (not logged in )

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#106]
- not logged in -> not all datsets
- log in -> all datsets listed
- **log out -> all datasets listed**

![image](https://user-images.githubusercontent.com/15946467/43255881-52f366e4-90cb-11e8-9be3-16d97fc864ab.png)

![image](https://user-images.githubusercontent.com/15946467/43255920-68f79604-90cb-11e8-9491-f753dffd2925.png)

**Comment by DavidBlaa** [comment]
I can not reproduce it either in the test maschine or in my locale version.
I think that in your version that routing has been changed and the logout goes to the search and not to the public search.

That means, the search is public as well.
Can you check it out and / or come over to me.

**Comment by geofranzi** [comment]
Now I know why ...... It is because of that not so nice behavior, that if you log in/log off you are always have to start at the beginning, which is currently the public data page. This created the confusion. As far as I understood in the test version permission not checked ...that's the reason everything is always visible I guess. So everything is ok.

**Comment by DavidBlaa** [comment]
That would be nice, but I think that is not the solution yet.
When I am working locally in the debug this is correct for me.
So on the public side only public datasets are displayed. whether logged in before or not.

**Comment by DavidBlaa** [comment]
in the current test, the basic search was defined also as a public features.
this is not the correct behavior. 

i changed the search page tonot public.

**Comment by shahab-ab** [comment]
After I changed search page to not-public, the problem was resolved. Is this the default solution for this? As I we're currently on 2.14.4, we expected this bug have been already resolved.
BR
