### ISSUE TITLE
WebShell UI: Allow owner to delete unstructured primary data

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#107]
Would be good if the owner could at least delete unstructured primary data.

![image](https://user-images.githubusercontent.com/15946467/43262389-3c8b8624-90e0-11e8-9ac8-329c2afef3b6.png)

**Comment by DavidBlaa** [comment]
in the new version the multimedia module is now inserted and defined as standard. Therefore I give the task to @MaJoHo .

**Comment by geofranzi** [comment]
closed with https://github.com/BEXIS2/Core/issues/373
