### ISSUE TITLE
DCM - Attachments list shows empty artifact at start

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#108]
- without adding or deleting a file one "ghost"-entry is shown as "deleted"

![image](https://user-images.githubusercontent.com/15946467/43262585-f7027a80-90e0-11e8-8ef7-5cc92e34e6ff.png)

**Comment by matparsa** [comment]
this issue should not exist in the current version.
![image](https://user-images.githubusercontent.com/14373134/43709015-0cdb43ee-996c-11e8-8e82-1fd7813e2472.png)

**Comment by DavidBlaa** [comment]
#139

**Comment by navabpourn** [comment]
It exists in RC3.

**Comment by romangerlach** [comment]
solved
