### ISSUE TITLE
Rename purge and delete dataset

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1098]
Proposed renaming:

- Purge -> Delete (Delete a dataset permanently)
- Delete -> Hide (Hide dataset from search; direct access via URL still works)

**Comment by CFuerstenau** [comment]
I would prefer:

- Delete -> Archive

**Comment by aostrow** [comment]
Delete -> Withdraw

**Comment by geofranzi** [comment]
Bassed on the decision in the data curator coffee renaming is not wanted.
