### ISSUE TITLE
Adjust Text for deleted datasets and add reason

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1099]
- [x] Change Current: Dataset is in processing" to "**Dataset is deprecated**". -> wait for text approval from data curatos
- [x] "... . Reason: [text from db]
- [x] add db field for a reason? -> not needed (use existing modification comment)

**Comment by aostrow** [comment]
Suggestion for text (also given to curators):
The dataset has been withdrawn. Reason: xxx. Please check the 'Links' section if a new version is available.
