### ISSUE TITLE
WebShell - Revise account registration info text

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#110]
- [x] Info Text after account creation:
_Information:
Before you can log in to complete your registration please check your email and verify your email address._ 

- [x] Error message, if email address was not confirmed
give a more precised info to the user (e.g. email address not verified, account deactivated ....) instead of  “_An error occurred while processing your request_.” 

- [x] Adjust verify mail address mail
Subject: _BEXIS Account registration - Verify your email address_ 
Body: _Dear user,_

_please confirm your mail address and complete your registration by clicking here. Once you finished the registration a system administrator will decide based on your provided information about your assigned permissions. This  process can take up to 3 days._

Sincerely yours, 
BExIS Team_

(ideally replace BEXIS with individual instance name e.g. iDiv Biodiversity Data Portal)

**Comment by navabpourn** [comment]
Tested in RC4. 
There is no need to write "welcome" in the title. (It is my opinion)
The body of the email is again "Please confirm your account email address by clicking here".
