### ISSUE TITLE
Metadata xsd element type "xs:boolean" is not working

### ISSUE THREAD

**Issue by mguderle** [BEXIS2/Core#1106]
### Is there an existing issue for this?

- [X] I searched for a similar issue and didn't find a suitable one.

### What is going wrong?

We use in the ATTO Data Portal Metadata Structure one element with type "xs:boolean" to ask the user if the data are part of a PhD thesis. Since the last update to 2.17.1 this element is not active in the metadata.

### How is it supposed to work?

The element should be active so that users can click it if data are from a PhD thesis

### Do you get any exceptions?

No

**Comment by DavidBlaa** [comment]
![image](https://user-images.githubusercontent.com/19665289/231119264-11048d02-7e58-48f6-9c55-66ad3c0484ec.png)


ich glaube das problem ist, 
das bool immer deaktiv ist, weil es schon reicht, dass das attribute gesetzte wird, selbst wenn der wert leer ist.

**Comment by mguderle** [comment]
Es hatte aber bisher immer funktioniert, David.

**Comment by geofranzi** [comment]
The element is disabled or missing?

**Comment by mguderle** [comment]
![20230406_094246](https://user-images.githubusercontent.com/36069971/231125058-ccc0a573-7d01-474d-80bb-3d337211e0cd.jpg)

**Comment by mguderle** [comment]
Element is disabled
