### ISSUE TITLE
DCM - Correct upper / lower case writing of field titles

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#111]
DCM - BeXIS.Modules.Dcm.UI - Views - Form - _metadataAttributeView.cshtml:

replace: 
`foreach (char letter in Model.DisplayName)
    {
        ......
    }
`
by
 
    // Add before every uppercase word empty space (e.g. LastNameTEST -> Last Name TEST)
    displayName = Regex.Replace(Model.DisplayName, "((?<=[a-z])[A-Z])", " $1");
    
    // split at " "
    string[] wordList = displayName.Split(new char[0]);

    // lowercase all words, except of uppercase abbreviations (e.g. URL)  
    for (int i = 0; i < wordList.Length; i++)
    {
        if (wordList[i].ToUpper() != wordList[i])
        {
            wordList[i] = wordList[i].ToLower();
        }
    }

    displayName = String.Join(" ", wordList);
    
    // Make first char uppercase
    displayName = char.ToUpper(displayName[0]) + displayName.Substring(1);`

**Comment by DavidBlaa** [comment]
Solved in 2.12 RC2

**Comment by navabpourn** [comment]
The code is replaced, but I don't understand what should test in the application.

**Comment by navabpourn** [comment]
The texts close to fields should write in correct English like "First name" instead "First Name".
That is fine :)
