### ISSUE TITLE
DCM - Choices - Unselected node is not removed

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#113]
After changing to second option previous selected node and values still exist

![image](https://user-images.githubusercontent.com/15946467/43270248-dfd7f646-90f4-11e8-9f47-ba8a15936d42.png)

**Comment by navabpourn** [comment]
@geofranzi Could you please check also this issue? Thanks.

**Comment by geofranzi** [comment]
Works fine in rc3
