### ISSUE TITLE
Setup initial theme.css

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1137]
Create a theme close to the current layout (https://www.skeleton.dev/docs/generator)

- [x] store theme in bexis-core-ui
- [x] create a example page in bexis-core-ui for the overview

**Comment by zxyctn** [comment]
This one has the current colors of the system:
https://github.com/zxyctn/skeleton-todo/blob/main/src/app.postcss

You can see this theme in use here:
https://skeleton-todo.vercel.app/
