### ISSUE TITLE
Shell Settings: Refactoring from sveltstrap to skeleton

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#1150]
- [x] #1163
- [x] #1162
- [x] form with primitive data types (string, number, boolean)
- [x] form with complex data types (arrays, objects)
- [x] persistent save of modified values (throughout the different modules)

**Comment by DavidBlaa** [comment]
- add new type like object that contains json for complex setting beside keyvalue pair

**Comment by sventhiel** [comment]
Beside basic/primitive data types (by using different input fields from bexis2-core-ui library), there are options (i.e. selection list) and JSON code editor. So far, no further types are included.
