### ISSUE TITLE
SAM: Issues in User and Group Management

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#118]
Are these issues bugs?
- A duplicate name is allowed, not by creating, but via editing.
- Extra blank spaces in a name of a group are allowed. That means "myGroup" is count different as "myGroup   ".
- The same issue appears in the User Management. Blank spaces at the end of a username or an email are allowed. Therefore I am able to create two users "nafiseh" and "nafiseh " to look the same.

**Comment by sventhiel** [comment]
Well, it seems to be a never ending story. I guess we had that issue already several times. At the end, I don't know, why that strange behavior is still (or again) possible, but I am going to fix it (again) - before the next release.

**Comment by sventhiel** [comment]
This should be fixed within the next release - if tests run successful.

**Comment by geofranzi** [comment]
works
