### ISSUE TITLE
error in creating a unit 

### ISSUE THREAD

**Issue by arefeh-b** [BEXIS2/Core#119]
When creating a unit, an error occurs: 
<img width="391" alt="1" src="https://user-images.githubusercontent.com/11985137/43370511-6ef2fd66-9380-11e8-98c9-aaef4ccfd9ec.PNG">
But the unit exists in the list of created units.

 - OS: Windows 10
 - Browser: Chrome
 - Version: 67

**Comment by navabpourn** [comment]
But the unit is created and it is on the list.

**Comment by navabpourn** [comment]
No error in RC2. Thanks :)
