### ISSUE TITLE
Dataset Attachment: Typo in term "attachment"

### ISSUE THREAD

**Issue by aostrow** [BEXIS2/Core#1194]
There is a t too much in the word. For both cases, "uploaded" and "deleted."
Attach**t**ment instead of Attachment

**Comment by geofranzi** [comment]
In history? I could only find it in the send emails...

**Comment by aostrow** [comment]
![grafik](https://github.com/BEXIS2/Core/assets/26480843/6adeba7f-b87d-4c43-9950-ff51637ba632)

**Comment by geofranzi** [comment]
ok, this is fixed with the commit
