### ISSUE TITLE
System logging / failure logging functionality

### ISSUE THREAD

**Issue by jbiermann** [BEXIS2/Core#12]
Please provide a configuration option on logging errors to file (e.g. strack traces). The logging data within Workspace\General\Logging isn't very helpful in tracing problems. Please provide a file logger which can be configured (e.g. just info messages, error, stacktraces etc.) 

#11

**Comment by javadch** [comment]
This feature is meant to be used by the core dev team. In order to obtain more information please use the log entries written to the database. They are in logEntries table. You can set logging options in the web.config
