### ISSUE TITLE
The metadata form does not accept new names

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#125]
I can not fill in fields with a name that is not yet registered as a party.
Is it our policy or a bug?

**Comment by DavidBlaa** [comment]
its a bug and nearly fixed :D

**Comment by DavidBlaa** [comment]
available in v2.12 rc3

**Comment by sventhiel** [comment]
Change formular into form.

**Comment by navabpourn** [comment]
It is tested and works. Thanks :)
