### ISSUE TITLE
DCM - DevReview - Issues - List

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#1272]
> after a review with internal developers, the following issues came up that need to be worked on

### Selection
- [x] set clear buttons next to selection buttons with divider
- [x] set save button bottom right
- [x] check button against color rules
- [x] add to all buttons a title
- [x] row infos (total, found,skip) next to to table
- [x] add info, you see only the first 10 rows of the data
- [x] remove selection support and aktivate it as default
- [x]  2 Section over the table, Selection and Information (controls card should start from top)
- [x] Fix : Subset selection with emtoy fields not working well, sometimes
- [x] May DisplayPattern are not set during the creation (show data not using display pattern)

### Suggestion / creation
- [x] data preview - shrink text if value is to long 
- [x] toggle between detail and overview

## Entity Template
- [x] confirm cancel during delete also delete the entity template
- [x] edit entity template, sometimes validation triggers, name allready exist
- [x] all buttons on the right side (from right to left -> save,cancel)
- [x] mutli selection of file types break the form after trying to edit again
- [x] data structure write apart
- [x] card - metadata structure as label
- [x] header of card -> flex not grid, title not flex

## Create
- [x] Load Page -> Test text is shown
- [x] if no required fields are set in the template, create should also work
- [x] position of the creation spinner -> next to the buttons
- [x] buttons style (see rules) and position -> right, first save then cancel

## Edit
- [first load -> for each error on server -> set into a new issue 
- [x] submit, confirm text -> copy - change it
- [x] all last modified: add title "last modified"
- [x] all last modified: check if possible to move below title on left

### Data Description
- [x] Fix: Delete button not shown when data does not exist and show if data exit

### Title -> ID | Title
- [x] remove the input field and replace it with id | title

### Upload
- [x] File Reader -> File Reader Information
- [x] Change to: please select a file to set/update the file reader information
- [x] Fix typo: Seperator -> Separator
- [x] Change divider from / to | (Separator | Decimal | Text Marker: ...)
- [x] Adjust Text to (Core? -> also for attachments): 
![image](https://github.com/BEXIS2/Core/assets/15946467/b1b0bcd1-de56-417e-bcb8-458ca6502311)

### Validation
- [x] if possible, unify the style 
![image](https://github.com/BEXIS2/Core/assets/15946467/77ea234d-154c-4765-a35b-62affe8f0ba8)

**Comment by geofranzi** [comment]
for discussion:
![2023-08-01 17_28_03-Edit](https://github.com/BEXIS2/Core/assets/15946467/2cc72b09-0975-4b9d-bb11-209b0221d130)
