### ISSUE TITLE
Tenant theme configuration does get ignored

### ISSUE THREAD

**Issue by jbiermann** [BEXIS2/Core#13]
There seems to be an issue regarding theme configuration for tenannts. The settings get totally ignored (e.g.  <Theme>Office2010Silver</Theme> will still use the default theme). 

Also placing a custom themes within the theme folder of the tenant does get ignored.

**Comment by romangerlach** [comment]
themes are an unattended feature without any official support. We take a look and decide whether we have to remove it or adapt it.
