### ISSUE TITLE
Dataset request with a reason text field 

### ISSUE THREAD

**Issue by EleonoraPetzold** [BEXIS2/Core#130]
A user would like to enter a text where a description is provided why and for what the data is needed.
This text should be send in the request mail to the Owner and is visible in open reqests. 

This issue is related to #31

Add a comment field for permission requests.

- [x] Add field to database
- [x] Show text area for request comments before request button
- [x] Add request text to email notification
- [x] Show request text

**Comment by DavidBlaa** [comment]
test case is in the test quality tool
