### ISSUE TITLE
Issue while Download Dataset

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#131]
The following download process by using the Download Dataset button does not include the data file:
- Download Dataset with Excel
- Download Dataset with Template (template file has no data inside)
- Download Dataset with TSV

**Comment by DavidBlaa** [comment]
available in  2.12 RC3

**Comment by navabpourn** [comment]
Download with Excel and TXT does not work in RC3.

**Comment by DavidBlaa** [comment]
works in v2.12 rc4
