### ISSUE TITLE
[RPM] Data Structure Creation Review Issues

### ISSUE THREAD

**Issue by sventhiel** [BEXIS2/Core#1354]
- [x] #1358
- [x] #1357
- [x] #1356
- [x] #1355
- [x] set a cross to all invalid variables and color them red (dezent)

**Comment by DavidBlaa** [comment]
![image](https://github.com/BEXIS2/Core/assets/19665289/4614844f-a336-493e-ac92-417a24169929)

this background not working well, thats why i decide to only work with the xcross as error mark.
