### ISSUE TITLE
Empty files are attached automatically to my dataset

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#137]
There were 3 empty files and I deleted one of them.
I am not able to reproduce it.

![attached](https://user-images.githubusercontent.com/20185586/43950120-c65fe2ae-9c8f-11e8-81b2-bcea0f6c880d.png)

**Comment by matparsa** [comment]
It should be fixed in the next publish

**Comment by DavidBlaa** [comment]
works but a other issue appears #152
