### ISSUE TITLE
DCM - Attachments (some errors and suggestions)

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#139]
- [x] Rename table header "Your Files" in "Attached Files" ("your" is only correct looking at my own datasets, but in the most cases this will be wrong)
- [x] Remove /Hide the ID column or rename to Number (No.) - it is not a ID as it changes if you delete a file ...
- [x] Rename "Push" to "Upload" (the word "push" is a technical word and not intuitive to understand for a normal user)
- [x] Revise explanation text (shorten the text, otherwise it will be never read):
    - "Please select one or more data files to be uploaded to this dataset. If you upload multiple files with one description, they all will have one description." 
e.g. to: "You can select one or multiple files. Please provide a short description for your selected file(s)."
    - "Note: Large data files may take several minutes or hours to transfer, depending on your network speed.
The system is freezed until the file has been transfered completely. Please be patient!"
-> _Note_: Depending on your network connection the upload may take some time. Please stay patient.
(to mention a time like "hours" is demotivating to try ;-) ..as long as their is a gif shown the current page freeze (I could not test due to the current file size limit) I think we do not need to explain it. 

- [x] Error message: "Max file : 1024 MB is supported. Please contact your administrator to upload bigger files." -> "Maximum file size exceeded. The maximum support file size is 1024 MB. Please contact your administrator to upload bigger files."
- [x] Currently the max file size is not checked correctly. I tried to upload a 2 MB file and I got the error it is too big

**Comment by matparsa** [comment]
all the issues were fixed

**Comment by arefeh-b** [comment]
I uploaded 800 MB files and it worked fine!
