### ISSUE TITLE
Main Menu - 2 or more line header overlay content

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#142]
once you have several additional modules in the header it is very likely the header span over two or more lines. Currently this is a overlay on the main content and makes the first lines not accessible.

**Comment by sventhiel** [comment]
That is true. We will fix the menu bar asap.

**Comment by geofranzi** [comment]
change padding with javascript on window resize

or 

possible solution without javascript (add invisible 2nd menu)(https://codepen.io/parkerbennett/pen/hbzJm)
- remove padding 50px from body
- add second menu before `<div class="container-fluid" style="/* margin-top: 36pt; */width: 100%;">` in _Layout.chtml
- add  visibility: hidden; position: unset; to 2nd menu

**Comment by DavidBlaa** [comment]
tested in 2.12.2

**Comment by geofranzi** [comment]
window resize did not work in Chrome
replace by    `$(window).resize(function () {`

works in Chrome, FF and IE 11
