### ISSUE TITLE
Domain List from Api (internal) -> copy from data

### ISSUE THREAD

**Issue by MaJoHo** [BEXIS2/Core#1421]
- [x] fill the Domain List from a column from a dataset
- [x]  store origin of domain list

**Comment by MaJoHo** [comment]
![image](https://github.com/BEXIS2/Core/assets/3024715/5df2f4b6-cf9c-4e46-b87e-cbb2748bf514)

origen ist only strored and visible in the DB so far

**Comment by DavidBlaa** [comment]
fine 👯‍♂
