### ISSUE TITLE
Menu - Hide menu entries without permission 

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#143]
It would enormously increase the usability / reduce complexity presented to a user, if menu items a user do not have the permission for are not shown. 

Examples are the "Dashbord" or "Admin Wheel" which should be not shown to normal user, who just search for data. However, a general approach looking at the permission (and not just on logged in or not) is preferable.

**Comment by sventhiel** [comment]
You are right, security trimming in the menu is a valuable thing. But because of our deadline, we will postpone it after the current release 2.12.

**Comment by DavidBlaa** [comment]
test case is in the test quality tool
