### ISSUE TITLE
Remove or relink buttons in dataset view that goes to edit/upload

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#1433]

**Comment by DavidBlaa** [comment]
attachments , remove upload function

**Comment by geofranzi** [comment]
![image](https://github.com/BEXIS2/Core/assets/15946467/33615ae1-0520-438d-9edf-6727557bff18)

**Comment by geofranzi** [comment]
![image](https://github.com/BEXIS2/Core/assets/15946467/2e3e4c28-4d45-4e95-aff0-2fb2be6b59e4)

**Comment by DavidBlaa** [comment]
fixed
