### ISSUE TITLE
Error while normal upload Data

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#144]
I am not allowed to attach XLSM to the issue and also it is not possible to make a zip file from my data. Anyway, following is the data and it will fit to the Focal Mechanism data structure (RC3). 
While normal uploading dataset, after validation and before showing Summary, the procedure is blocked. 
An screenshot of the error message is attached.

602546370 | GCMT | 41328 | 13.93 | 51.56 | 21.80
-- | -- | -- | -- | -- | --
603161566 | NEIC | 41421 | 14.49 | 53.94 | 11.00
603229581 | GCMT | 41466 | 12.83 | 48.02 | 12.00
603229686 | GCMT | 41466 | 12.73 | 48 | 12.00
603230466 | GCMT | 41466 | 13.27 | 50.3 | 12.00
603735879 | GCMT | 41561 | 13.64 | 51.37 | 27.60
604717692 | GCMT | 41796 | 14.7 | 54.42 | 20.50
604717714 | GCMT | 41797 | 14.67 | 54.52 | 12.00
606747666 | GCMT | 42059 | 13.19 | 50.72 | 12.10
606748456 | GCMT | 42059 | 13.32 | 50.71 | 12.40
607395240 | GCMT | 42198 | 12.18 | 46.3 | 17.00
607643749 | GCMT | 42198 | 12.13 | 46.41 | 20.80
607396169 | GCMT | 42198 | 12.18 | 46.31 | 17.70
607668046 | GCMT | 42233 | 13.82 | 51.59 | 19.80
607725347 | GCMT | 42249 | 14.26 | 53.49 | 12.00
607725357 | GCMT | 42249 | 14.32 | 53.31 | 12.00
607780211 | GCMT | 42269 | 13.28 | 50.75 | 12.00
607832501 | GCMT | 42274 | 13.27 | 50.85 | 13.60

![error_upload](https://user-images.githubusercontent.com/20185586/44137622-5f9df728-a071-11e8-8cd9-e9666a01b369.png)

**Comment by navabpourn** [comment]
After that, I met this server error.

![error-upload2](https://user-images.githubusercontent.com/20185586/44137925-6c2c7932-a072-11e8-8df2-02ebb9ec1f77.png)

**Comment by DavidBlaa** [comment]
fixed in v2.12 rc4

**Comment by navabpourn** [comment]
The first error happens again in RC4 :(
