### ISSUE TITLE
Title and favicon of tab in svelte pages are not  correct

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#1472]
- [ ] load fav icon in tab
- please check, where the title is set, may we need to use a other format

**Comment by sventhiel** [comment]
Currently, there are differences even for different svelte pages - e.g. https://dev.bexis2.uni-jena.de/dcm/create/ and https://dev.bexis2.uni-jena.de/settings/. Although the first one does not show/load the favicon, it is working for the latter one.

![image](https://github.com/BEXIS2/Core/assets/55701246/7888abd3-5c4c-4e72-9da4-6c95d687f662)

![image](https://github.com/BEXIS2/Core/assets/55701246/7b97d9eb-3ae1-48f5-b58d-5d9859a00df4)
