### ISSUE TITLE
AccountPartyTypes defined two times

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1482]
both are used?
![image](https://github.com/BEXIS2/Core/assets/15946467/60db9254-2232-4dd8-a282-779a94b3ec93)

**Comment by sventhiel** [comment]
Currently, I do not know which property is considered in all/most cases. So, I'll try to find out and remove the redundant data later on. In case the settings are not used, should it be transferred from web.config to bam settings?

**Comment by geofranzi** [comment]
Sieht so aus, als ob nur das was in der web config drin steht da auch verarbeitet werden kann. Ein einzelnen Begriff ist da nicht vorgesehen

![image](https://github.com/BEXIS2/Core/assets/15946467/9be1ccd1-68d8-4e32-ab1c-c5d2ae94cb46)
