### ISSUE TITLE
Meaning Seed data

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1499]
- [ ] seed data for relationships, prefix, ...

**Comment by DavidBlaa** [comment]
some ideas here?

**Comment by geofranzi** [comment]
https://i-adopt.github.io/#/hasContextObject
https://i-adopt.github.io/#/hasMatrix
https://i-adopt.github.io/#/hasObjectOfInterest
https://i-adopt.github.io/#/hasProperty
