### ISSUE TITLE
hard coded CSS style information (inline styles) in default theme

### ISSUE THREAD

**Issue by jbiermann** [BEXIS2/Core#15]
While customisation the look of the GUI I have noticed that on several cshtml template files there is hardcoded CSS style information inside the HTML elements. 
This is bad for customisation, since I just can't change the CSS files. I have to mess around with the HTML files, too.
Please remove any inline styles from default theme.

Example: file _Menu.cshtml  contains style="background-color: #eff7f6"

**Comment by romangerlach** [comment]
- [ ] views should not contain css
- [ ] module level css files should have a naming convention
- [ ] every module developer is responsible for cleaning up css and html files

**Comment by navabpourn** [comment]
Attached is a list of style definitions inside the code.
[Style_Inside_Code.xlsx](https://github.com/BEXIS2/Core/files/2083175/Style_Inside_Code.xlsx)

**Comment by geofranzi** [comment]
having it sorted is still relevant, but with UI change to Svelte custom CSS will be stored within component.
