### ISSUE TITLE
Different format of writing the date in German and English version is the cause of the error in the Excel template

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#150]
The date is saved in my document in the format 20.06.18 and when I copy it and paste it into the downloaded excel template, it is saved as an hour.
If I change the format of my document and write 20/06/28, then the copy and paste works.

![date](https://user-images.githubusercontent.com/20185586/44334378-a3226480-a471-11e8-8f04-9fe99d88eb54.png)

**Comment by DavidBlaa** [comment]
it was a excel template issue and its fixed now.
the file is in the workspace of 2.12.
