### ISSUE TITLE
When setting rights on datasets, the READ permission is either not set or not shown, or both.

### ISSUE THREAD

**Issue by javadch** [BEXIS2/Core#151]
**Describe the bug**
According to #40 and #31, when a dataset is created, some rights should be automatically assigned. It seems that the READ permission is not assigned, hence, the OWNER cannot access the dataset.

**Comment by sventhiel** [comment]
There was an issue with the "PartyTypes.xml". The definition of PartyTypePairs didn't contain the "Read" access right.

**Comment by navabpourn** [comment]
I have tested it in that way in RC6:
User 1 is the owner. S/he has all access to the dataset. 
For the non-owners, I have to set rights by clicking on the checkboxes.
