### ISSUE TITLE
Log Off does not work in Svelte Layout

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1518]
![image](https://github.com/BEXIS2/Core/assets/15946467/ba34b782-1ec5-40d6-8d36-05cbcf2ae9ed)

**Comment by sventhiel** [comment]
Similar to #1520

**Comment by sventhiel** [comment]
Even after changing the url of the menu item, _**logout**_ isn't working. This is because the menu items are rendered as HTTP GET functions only. But _**logout**_ is meant to be HTTP POST. So, beside title, url and module, it should contain information about the HTTP method.

**Comment by sventhiel** [comment]
We will go with either one of the following options:
1. change function to work as HTTP GET
2. change menu items to support HTTP POST
