### ISSUE TITLE
A User should only see files in Attachments.

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#152]
**Describe the bug**
It seems that the attachments page load all files of a dataset that are registered in the content descriptor.
But it should only load the files in the Attachments folder.

Dataset view:
![image](https://user-images.githubusercontent.com/19665289/44453405-43ef5c00-a5f9-11e8-94f9-bca1f78c9232.png)

Content Descriptor Table

![image](https://user-images.githubusercontent.com/19665289/44453618-c7a94880-a5f9-11e8-81de-8d471f93b5ed.png)

**Comment by javadch** [comment]
One possible solution would be to add a tag "Attachment " to the "name" field of the content descriptor record.
- [ ] Keep the file path relative to its dataset folder

**Comment by matparsa** [comment]
As the attached files are saved in a subfolder in dataset calling attachments folder, another solution is to show only the files which exist in this path.

**Comment by sventhiel** [comment]
Is there already a solution implemented?

**Comment by javadch** [comment]
I suggest that @matparsa looks at my proposed solution (3 comments above).

**Comment by navabpourn** [comment]
It is being tested in RC8. Now all attached and uploaded files are separated and displayed in the right places.
