### ISSUE TITLE
Token Link broken in Svelte layout

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1520]
![image](https://github.com/BEXIS2/Core/assets/15946467/91198a15-247e-4329-b9c3-c20a7eb4dbec)

![image](https://github.com/BEXIS2/Core/assets/15946467/b806f0a5-3a14-47ce-b367-3bdb16f71cc0)

**Comment by sventhiel** [comment]
Similar to all other links in the menu. If you are inside any module (page within that particular one) not only home, but most of the other links need to work from host/base and not from the module base path.

That's why the link in the screenshot is using both, rpm route plus shell route.

**Comment by sventhiel** [comment]
Even though the URL is working, the content is not correct. So please change it...
- [ ] add proper visualization of the JWT instead of showing an "empty" page.
- [ ] change/remove the form for validity of the JWT. So, users should not be able to change the value on their own.
