### ISSUE TITLE
Visualization Issues

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#153]
**Issue 1**
Currently the timestamp lastcheckiotimestamp is used for all cases in the visualization part.
But in the case of "when datasets are created", the function should use the timestamp of the first datasetversion of a dataset.

![image](https://user-images.githubusercontent.com/19665289/44571022-e0dc0180-a77f-11e8-8d03-e4e0fc6d5d83.png)

**Issue 2**
What the CheckIn and CheckOut view schould  visualize? 

![image](https://user-images.githubusercontent.com/19665289/44571002-d457a900-a77f-11e8-8488-2b923b412f52.png)

- [x] created datasets view should use the timestamp of the first datasetversion of a dataset
- [x] remove checkedOut dropbox options
- [x] refactor the checkedIn calculation

**Comment by DavidBlaa** [comment]
tested in rc 4 and create issue #153

**Comment by navabpourn** [comment]
Two first items will be available in RC5.

**Comment by navabpourn** [comment]
All will be available in RC6.

**Comment by navabpourn** [comment]
@arefeh-b Could you please test it? Thanks xx
