### ISSUE TITLE
Breadcrumb - Home to AppName

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#1537]
![Image](https://github.com/BEXIS2/Core/assets/19665289/16c6d41f-d8f8-4288-9360-374dfe01bb8a)

**Comment by sventhiel** [comment]
This should be fixed by this commit [f9f91b2](https://github.com/BEXIS2/bexis2-core-ui/commit/f9f91b262ce3271f9172c0a992c8275cf25de6c9). But at least the bexis2-core-ui needs to be published once again.
