### ISSUE TITLE
Can not create dataset in BEXIS2 3.0 demo instance

### ISSUE THREAD

**Issue by CFuerstenau** [BEXIS2/Core#1539]
### What is going wrong?

Page to create dataset with file or data template is loading forever
I logged in as data manager.

![grafik](https://github.com/BEXIS2/Core/assets/45873895/f5b7bfac-6d4c-4ad4-846b-7f9da2792a3c)

### How can it be reproduced?

1. Log in as data manager
2. Click Create
3. Choose File or Data

### What kind of system do you use?

- Browser: Firefox

**Comment by geofranzi** [comment]
Entity templates need to be saved again. It's probably still a problem with the seed data. The demo instance is fixed now.
