### ISSUE TITLE
Create data structure - match between unit and template not check if I select a new one

### ISSUE THREAD

**Issue by CFuerstenau** [BEXIS2/Core#1542]
**Is your feature request related to a problem? Please describe.**
- step 1: create data structure
- step 2: define variables
- Name: Ca, suggested unit: molg/kg; suggested template: amount of substance per mass
- want to change it to unit: g; template: mass
- have still the error message: unit not match with the template -> **which is wrong**

![grafik](https://github.com/BEXIS2/Core/assets/45873895/77714393-336d-4951-975e-1e7f6744540d)
![grafik](https://github.com/BEXIS2/Core/assets/45873895/7e2792fc-50ec-47a4-9700-528469de5da8)

**Describe the solution you'd like**
- would be nice to have the check between unit and template after changing them
- if not, there should not be an error message

**Describe alternatives you've considered**

**Additional context**

**Comment by geofranzi** [comment]
the mass template says kg ...not g
![image](https://github.com/BEXIS2/Core/assets/15946467/288844fe-66f7-4a1a-a05d-09ba7bcbba68)
