### ISSUE TITLE
Create data structure - would be nice to be able to type in the unit or template

### ISSUE THREAD

**Issue by CFuerstenau** [BEXIS2/Core#1543]
**Is your feature request related to a problem? Please describe.**
- step: defining the variable
- problem: have to select unit and template from list
- example: unit, type in g, have to select it from list

**Describe the solution you'd like**
- would be nice, if I could press enter, after typing in the unit and if it is part of the defined units

**Describe alternatives you've considered**

**Additional context**

**Comment by DavidBlaa** [comment]
you can use tab instead of enter to complete a selection in the input field.
can you please try whether this is enough for you?
