### ISSUE TITLE
Collection of small issues

### ISSUE THREAD

**Issue by CFuerstenau** [BEXIS2/Core#1545]
### What is your feature request all about?

All were found while creating the data structure/defining the variables. Some of them are only suggestions from my side.
- [x]  mouse over missing for trash and copy
- [x] the arrows next to trash and copy confused me using it the first time -> maybe put them under trash and copy 
- [x] Infotext: show all information about the units in a table Nothing found? Make a new suggestion. - Dot missing after "in a table"?
- [x] Infotext: Mark as part of primary keys - should be: mark a part of primary key
- [x] would be nice to have a save button also at the end of the data structure
- [x] shouln't it be detected as integer? 
![grafik](https://github.com/BEXIS2/Core/assets/45873895/5c55de53-53e9-447e-b201-d8230f86dc1b)
- [x] °C is not display right, makes problem creating a data structure and uploading data
![grafik](https://github.com/BEXIS2/Core/assets/45873895/6bf1bcc1-716d-4871-a12b-67e79b74ff00)
 - [x] suggestions for unit and template don't fit to each other; I would expect that they fit 
![grafik](https://github.com/BEXIS2/Core/assets/45873895/2d76fe63-445d-443c-8836-c7c8b7913b86)
- [x] use dimension of the unit to suggest template if
- [x] top 3 items should not came from the group others

**Comment by DavidBlaa** [comment]
shouln't it be detected as integer? -> i cant see the unit in this screen but i guess uint is not part of the unit, then it is a unit seed data problem.

**Comment by CFuerstenau** [comment]
the value has no unit

**Comment by DavidBlaa** [comment]
ah sorry, beacause there are only non negative integers the suggestion give you uint => from 0 ->....
Thats correct

**Comment by DavidBlaa** [comment]
°C - we need to talk, its a file settings issue
