### ISSUE TITLE
Data Out API vs Download: Replacement of missing values

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1548]
During download, missing values are replaced. They are not replaced by retrieving the data via the API.

- should they replace both the missing values before?
- if not, should the API have a parameter to request replacement?

**Comment by DavidBlaa** [comment]
there should, i wil check it now

**Comment by DavidBlaa** [comment]
![Image](https://github.com/BEXIS2/Core/assets/19665289/b37a30b4-12c9-4837-a095-cd9fa49ef39c)

**Comment by geofranzi** [comment]
changed in v3? If yes, we need to communicate during the release notes
