### ISSUE TITLE
New API: splitting names for retrieval of first, middle and last name(s)

### ISSUE THREAD

**Issue by sventhiel** [BEXIS2/Core#1550]
### What is your feature request all about?

Sometimes, you get only the full name of a person within BEXIS2. But for further processing, you need to separate the first, middle, and last name(s). Instead of doing that manually or through a self-designed method, it would be good to call an internal API.

### How could/should a solution look like?

The system should provide an open API to call so that a full name will be split accordingly.

**Comment by sventhiel** [comment]
The api is up and running. Because of the potential length of long names, I set the method to be HTTP POST instead of HTTP GET.

![image](https://github.com/BEXIS2/Core/assets/55701246/3df4867f-14c0-42d5-9456-6c31ef0462e0)

Please try out this curl example: `curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '"Florian Cloud de Bounevialle O%27Malley Armstrong"' 'https://dev.bexis2.uni-jena.de/api/names'`

**Comment by sventhiel** [comment]
This API should be renamed to a more meaningful name.

**Comment by geofranzi** [comment]
new name: 
**PersonNameComponents** 


person: contrast to species names
name:  singular -> only one name is decomposed
components -> result object are the components of one name
