### ISSUE TITLE
Metadata can not be edited

### ISSUE THREAD

**Issue by Yuan-yuan-Huang** [BEXIS2/Core#1557]
### Is there an existing issue for this?

- [X] I searched for a similar issue and didn't find a suitable one.

### What is going wrong?

When I try to create a Data file, and click edit metadata button, it returns to an Error page:
![image](https://github.com/BEXIS2/Core/assets/80970032/73c99cfe-7c6b-459f-907a-324f77754f98)
![image](https://github.com/BEXIS2/Core/assets/80970032/4a9888fb-eccd-4c45-8df4-adfc36dc5958)

**Comment by DavidBlaa** [comment]
fixed in demo and now also in dev for next release

**Comment by Yuan-yuan-Huang** [comment]
This works well with the GBIF metadata schema. 
I tried a new Entity template by using different metadata schema (JEXIS):
![image](https://github.com/BEXIS2/Core/assets/80970032/d6caef90-ca73-471f-b8c8-916fa50fad92)
In this case, I could not edit the metadata again:
![image](https://github.com/BEXIS2/Core/assets/80970032/8e8c2e27-27c6-41d2-a0b4-0eac33a8221c)

**Comment by DavidBlaa** [comment]
thx for the report again, i will check your xsd.
i changed also other mapping files so hopefully it will not appear any more.
