### ISSUE TITLE
Data Structure edit not found; New name for "Data Structure"

### ISSUE THREAD

**Issue by Yuan-yuan-Huang** [BEXIS2/Core#1560]
### What is going wrong?

Data structure can't be edited now.
![image](https://github.com/BEXIS2/Core/assets/80970032/820cb9ea-32fd-466e-91cd-936f482560b4)

Data structure now is renamed to "Data Description". Since Metadata (information about data, or description of Data) should also mean data description, we think the name is not so appropriate. I personally like the original word "Data structure". But name like "Variable Description" can also be considered.
But most importantly, this name should be consistent with the one on the right side button:
![image](https://github.com/BEXIS2/Core/assets/80970032/7d53d72a-02b9-48d9-98fc-7ee2e6c40045)

**Comment by geofranzi** [comment]
Editing everything related to a dataset is now only in one place possible: Dataset Edit View. You can switch to it using the toggle on the top right (we have an open issue to put an icon on it)
![image](https://github.com/BEXIS2/Core/assets/15946467/920dfac5-f271-47e0-a8e1-dee476abc59b)

**Comment by geofranzi** [comment]
I moved the naming to a new issue #1561

**Comment by geofranzi** [comment]
renaming done in #1561
