### ISSUE TITLE
Adjust UX writing under and for "Data Description"

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1561]
![image](https://github.com/BEXIS2/Core/assets/15946467/fe080e97-07f4-4bf2-9b5e-74d1c49c350b)

- [x] Rename "Data Description" back to "Data structure"
- [x] Correct UX writing for label
Select a Datastructure or generate from File
-> 

Generate based on an uploaded file, select an existing one, or create a new

**Comment by DavidBlaa** [comment]
commit added in this issue [#1283](https://github.com/BEXIS2/Core/issues/1283)
