### ISSUE TITLE
Delete Dataset related to an unstructured data structure does not work

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#158]
![deletedataset](https://user-images.githubusercontent.com/20185586/44709049-fbc4b380-aaa8-11e8-9065-b730b7c3e4f0.png)

**Comment by javadch** [comment]
It seems that after deleting an **unstructured** data structure the SyncView function is called. This function tries to synchronize the dataset in the materialized view with the tuples, but an unstructured does not have tuples and should be not be synced! 
Conclusion: the call to SyncView from the delete function of the unstructured data structure manager should be removed.

**Comment by navabpourn** [comment]
Testing Required in RC7

**Comment by javadch** [comment]
Fixing commit was not pushed. Merge commit cc20d379 and build and publish again before testing.

**Comment by navabpourn** [comment]
It works in RC8. Thanks :)
