### ISSUE TITLE
DB Update Script review

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1594]
- [x] Should we also have a creation/modification date here?

https://github.com/BEXIS2/Core/blob/bdaa82568ec40434a2a3c2b0481700ae7d42ac9d/database%20update%20scripts/Update_Script_2182to3beta.sql#L7

- [x] Set by default to "true": do we want this?

https://github.com/BEXIS2/Core/blob/bdaa82568ec40434a2a3c2b0481700ae7d42ac9d/database%20update%20scripts/Update_Script_2182to3beta.sql#L79

- [x]  Should we also have a creation/modification date here?
https://github.com/BEXIS2/Core/blob/bdaa82568ec40434a2a3c2b0481700ae7d42ac9d/database%20update%20scripts/Update_Script_2182to3beta.sql#L246

- [x] Duplicate 
https://github.com/BEXIS2/Core/blob/bdaa82568ec40434a2a3c2b0481700ae7d42ac9d/database%20update%20scripts/Update_Script_2182to3beta.sql#L709

**Comment by DavidBlaa** [comment]
a) we discused and descide, that meanings and templates do not need a creation/modification date.  (5 to 0)
b)Set by default to "true": do we want this? -> martin think conceptional correct is false but we decide true (5 to 0)
