### ISSUE TITLE
Import metadatastructure wizard HTTP 404 after last step 4

### ISSUE THREAD

**Issue by jbiermann** [BEXIS2/Core#16]
If I am going to import a metadatastructure (XSD) via settings -> manage metadata structure (http://example.com/dcm/ImportMetadataStructure/ImportMetadataStructureWizard) and follow the wizard the last step with the Finish button contains a wrong link (http://example.com/ddm/Home/ShowMyDatasetsInFullPage). You will get the default error page

```
Server Error in '/' Application.
The resource cannot be found.
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly.

Requested URL: /ddm/Home/ShowMyDatasetsInFullPage
```
The import itself has worked. It is only the broken link in the last step.

**Comment by DavidBlaa** [comment]
is fixed in 2.11.2
