### ISSUE TITLE
Not possible to empty Metadata fields in Firefox

### ISSUE THREAD

**Issue by aostrow** [BEXIS2/Core#1610]
### What is going wrong?

If I want to make a field in metadata empty, the content appears again after saving. 
It happens only in Firefox. 
The ValidateMetadataAttributeUsage ( jquery) does not start after emptying a field. It starts always if a make an edit and also if I empty a field in Chrome.

### How is it supposed to work?

Field should be empty or a warning for mandatory fields should show up.

**Comment by aostrow** [comment]
Ah, it seems to be a problem after 2024-01-30 (or later). 
Before it did work with BEXIS2 v18.2. 
Now not anymore.

**Comment by geofranzi** [comment]
I see in my Firefox it is triggered and sometimes returns 500 from the server in the BExIS, not on the demo. I also could empty fields in the demo instance with Firefox.

which fields are affected?

**Comment by aostrow** [comment]
Every field. I did it with https://demo.bexis2.uni-jena.de/ddm/data/Showdata?id=3

Here I emptied files "Sampling design" and clicked afterwards somewhere. No network traffic is visible.
![grafik](https://github.com/BEXIS2/Core/assets/26480843/f020609d-7a47-48dc-9be2-dfe16ac63a48)


If I let something in the field it is working:
![grafik](https://github.com/BEXIS2/Core/assets/26480843/21d07948-41aa-45ec-b6e3-04b29e35f39d)

**Comment by geofranzi** [comment]
I found out now: Text input fields trigger, but textarea fields do not. Can you confirm? 

![image](https://github.com/BEXIS2/Core/assets/15946467/5079ea1e-9d13-410d-8c5e-756370e804ab)
![image](https://github.com/BEXIS2/Core/assets/15946467/8797fd22-3d66-4006-95f0-397925b30ee4)
