### ISSUE TITLE
Access to the "Manage Documents" and "Files List" is denied

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#165]
**Describe the bug**
The options for accessing "Manage Documents" and "Files List" are missing in the list of feature permissions.

**Comment by matparsa** [comment]
It has been added to the feature permission.

**Comment by sventhiel** [comment]
In this case, it wasn't pushed to the release branch. Because even in rc6, this wasn't working and there were no registration of a feature and/or the corresponding operation/controller.

I added it now, so within the actual release or next candidate, it is inside the seed data.

**Comment by romangerlach** [comment]
still producing an error (both Manage Docuement & Manage Files:

![grafik](https://user-images.githubusercontent.com/16701900/45426056-670ea800-b69b-11e8-9164-642e18088a40.png)

**Comment by sventhiel** [comment]
@matparsa: Could you please provide the missing files?

**Comment by matparsa** [comment]
[Catalog.zip](https://github.com/BEXIS2/Core/files/2378687/Catalog.zip)
Path and the file exist in the compressed file or the catalog.xml should be in Workspace\Tenants\bexis\files\catalog.xml

**Comment by navabpourn** [comment]
They are accessible in RC8 :)
