### ISSUE TITLE
Non included ranges for a variable are not considered

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#167]
The dataset looks like the table below. The age should be less than 12 or more than 34 (not included).

![const2](https://user-images.githubusercontent.com/20185586/45208878-ecedb600-b28b-11e8-97e6-16191b7279f3.png)

The following errors are not included 12 and 34.

![const1](https://user-images.githubusercontent.com/20185586/45208880-eeb77980-b28b-11e8-9a70-fc679ac66e4f.png)

**Comment by MaJoHo** [comment]
There is no implementation for constraints in the Excel template so far.
I'm also not sure if it is posible with Excel.
