### ISSUE TITLE
Upload data: variable names with double quotes in csv file can't be imported

### ISSUE THREAD

**Issue by jbiermann** [BEXIS2/Core#17]
I have defined a custom data structure
say for example structure "teststructure"
with a few variables like data1, data2, data3

Now I have created a new data set for this structure and I want to upload a csv file which looks like this
```
"data1"	"data2"	"data3"
1.054	2.069	0.0411
6.0879	2.1	3.0
```

In the import wizard I have selected that the columns are seperated by tab. I have changed the TextMarker to doubleQuotes and selected my just created data set. During the Validation Step it complains that
```
A variable of the data file does not exist in the data structure : "data1"
A variable of the data file does not exist in the data structure : "data2"
A variable of the data file does not exist in the data structure : "data3"
```
The import only works if I remove the double quotes from the header line:
```
data1	data2	data3
1.054	2.069	0.0411
6.0879	2.1	3.0
```

I guess this is a bug. It is the same behavior in version 2.11 and 2.11.1

In the debugger I can see that it could load the header row, but the string still looks escaped `\"data1\".`

**Comment by DavidBlaa** [comment]
test case is in the test quality tool
