### ISSUE TITLE
Loading time for subjects

### ISSUE THREAD

**Issue by EleonoraPetzold** [BEXIS2/Core#171]
When I have a lot of subject (in our case 900) the system need nearly 1 minute to lead all items.

This problem occurs in:
- manage features
- Show dataset -> Dataset Permissions

When I try to filter the subject the system need a lot of time, too.

**Comment by sventhiel** [comment]
We are going to implement it with server-side paging/filtering/sorting. Stay tuned for updates.

**Comment by DavidBlaa** [comment]
test case is in the test quality tool
