### ISSUE TITLE
External Links as seed data?

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1784]
Should we add DWC & i-Adopt terms to our seed data?

**Comment by DavidBlaa** [comment]
dwc allready exist

![image](https://github.com/user-attachments/assets/6bf26f94-7f16-4eda-8f27-33b143004f13)


but it can be more

**Comment by geofranzi** [comment]
It's empty in the dev instance ...

**Comment by DavidBlaa** [comment]
then you found a bug, it should be there
