### ISSUE TITLE
Upload data to an unstructured dataset adds an empty file to the attachments

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#179]
If I upload a file to an unstructured dataset, an empty file will attached to the dataset.
If we would like to have both upload and attach for unstructured datasets, the uploaded file should not add to the list of attachments.
NOTE: It is tested by running the code of realease2.12 after publishing the RC6 in debug mode.

<img width="864" alt="attach empty" src="https://user-images.githubusercontent.com/20185586/45424303-61fb2a00-b696-11e8-89ad-79a1bd8aeb4b.png">

**Comment by sventhiel** [comment]
Please look at #152.
