### ISSUE TITLE
Manage unit (edit a unit) uncheck a datatype has no effect

### ISSUE THREAD

**Issue by jbiermann** [BEXIS2/Core#18]
I have created a new unit and selected a datatype for it. I have noticed that I have selected the wrong data type. Therefore I edit the unit, uncheck the wrong datatype and select the correct type. Then I click save.

Actual result: My unit has now both data types, the old one and the new one.
Expected result: I have unchecked the old one during edit and I expect that it has only the new data type.

**Comment by DavidBlaa** [comment]
works in v2.12rc4
