### ISSUE TITLE
Search only shows public datasets

### ISSUE THREAD

**Issue by romangerlach** [BEXIS2/Core#180]
the regular Search does not show all datasets (without query);

(there are actually 3 datasets); visible on Dashboard

![grafik](https://user-images.githubusercontent.com/16701900/45425410-8d334880-b699-11e8-9e4a-c561f88eae5d.png)

**Comment by sventhiel** [comment]
Currently, the landing page is "/DDM/PublicSearch/Index". But in case it should depend on authentication information of the user if he/she gets forwarded to "Public Search" or "Search", probably a redirect is necessary. 

Locally, I added such a redirect inside the method `BExIS.Modules.Ddm.UI.Controllers.PublicSearchController.Index()` at the beginning. `return RedirectToAction("Index", "Home", new { area = "DDM" });` should do the trick. But unfortunately, as a result, the system throws the following error.
![image](https://user-images.githubusercontent.com/11521044/45631251-cf45fb00-ba9a-11e8-9ca4-e54107556867.png)

So my guess is, that the `this.Render(landingPage.Item1, landingPage.Item2, landingPage.Item3);` inside `BExIS.Web.Shell.Controllers.HomeController.Index()` could not handle the additional redirect. So is there any advice how to handle that extra redirect? In general, both functions are returning a simple view.
