### ISSUE TITLE
After creating an unstructured dataset, editing of metadata not available

### ISSUE THREAD

**Issue by romangerlach** [BEXIS2/Core#182]
- created an unstructured dataset (ABCD, none)
- Edit, Copy Buttons are greyed out as if dataset permissions are not set correctly
- also there is no link to the Upload data, as within structured datasets

![grafik](https://user-images.githubusercontent.com/16701900/45426666-26179300-b69d-11e8-8a43-7cc3462a36dc.png)

- works fine when comming from the Dashboard 

![grafik](https://user-images.githubusercontent.com/16701900/45426892-bf46a980-b69d-11e8-83a8-f1677dc0d279.png)

**Comment by navabpourn** [comment]
The edit button is no available, but clicking on the Save button doe not save the changes.
