### ISSUE TITLE
Delete attachement from a dataset is defined by upload inside the database 

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#183]
Some of theme are deleted attachments

<img width="543" alt="datasetversionuploaddelete" src="https://user-images.githubusercontent.com/20185586/45426882-b9e95f00-b69d-11e8-8035-b28cd4b78fff.png">

**Comment by javadch** [comment]
The title does not explain what is the problem? and why a test has been done of the content of the database? Would the original author please explain the problem from a user's perspective?

**Comment by navabpourn** [comment]
It is not related to the perspective of the user. I found this wrong commenting on a test database when I tried to edit timestamps to produce a nice histogram for my presentation.
It does not matter if I upload or delete an attachment to a dataset, the comment is always "upload...".

**Comment by DavidBlaa** [comment]
test case is in the test quality tool
