### ISSUE TITLE
In case of a long list of menu items, the last items are hidden

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#185]
<img width="640" alt="gear" src="https://user-images.githubusercontent.com/20185586/45623436-9d776900-ba87-11e8-9ad1-1bbb5253c3f9.png">

**Comment by sventhiel** [comment]
Hi @navabpourn,
We are going to change the menu from "non scrollable" into "scrollable" as soon as possible.

**Comment by navabpourn** [comment]
It can open over the main window, a part of the main window or independently from the main window and scrollable.

**Comment by geofranzi** [comment]
#332 (it is now scrollable if its longer than 500px)
