### ISSUE TITLE
DisplayPattern Filter does not work correct

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#1895]
to fix: 
- [x] ":" should not be allowed for "date"
- [x] ":" must be in for "time"
- [x] (group name on top is static and not dynamic- always datetime)

![image](https://github.com/user-attachments/assets/feca7cdd-434d-4cfc-b733-3bc32bbcce3b)

![image](https://github.com/user-attachments/assets/1850934a-cd92-412c-8672-09be0c188749)

**Comment by DavidBlaa** [comment]
the groupname bounced to datetime as datatype in bexis, i will not touch it. special cases are not so cool
