### ISSUE TITLE
Automatic entry of system data in the metadata that can not be changed by the user

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#192]
There are system data partially present in the metadata. These must not be filled out by the users, but set by the system. Examples of such entries are ID, Version, Date of Last Modified

Tasks:
- [x] Collect a list a needed System Information
- [x] Advance the mapping to system entries
- [x] Advance the metadata form of system entries
- [x] Generate a function that updates the metadata with the system data

**Comment by geofranzi** [comment]
Information, which should be extracted 
[ ] Metadata creation date
[ ] Metadata: Last modified
[ ] Data: First data entry
[ ] Data: Last modified
[ ] Version 
[ ] (File name(s) from imported data files)

**Comment by DavidBlaa** [comment]
ready for testing.
(File name(s) from imported data files) is not involved. lats talk about this.

**Comment by DavidBlaa** [comment]
test case is in the test quality tool
