### ISSUE TITLE
Issue in edit a party

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#195]
Once I create a party I cannot edit its additional attributes. I can just change the name. By changing other fields a warning messages says that this party is already exist.

@DavidBlaa I assigned you, because I think Masoud is not more responsible for BEXIS issues.

**Comment by DavidBlaa** [comment]
Hey Nafiseh,

both in my local instance, as well as the demo editing the parties works.  We should look at the problem in your instance.

**Comment by DavidBlaa** [comment]
Tested by external user. Works!
