### ISSUE TITLE
Icons not loading on HTTPS server

### ISSUE THREAD

**Issue by MaSteinberg** [BEXIS2/Core#20]
Deploying the current version of BExIS on a server that serves the pages over HTTPS leads to icons not loading in modern browsers. This is due to the FontAwesome library being loaded in the file **bexis-font-awesome-extension.css** via a CDN that only provides HTTP access.
The CDN access should either be replaced with a different CDN (that provides HTTPS access) or the necessary files should be loaded locally.

**Comment by sventhiel** [comment]
Please check #14 reported by @jbiermann. It seems to be the same issue which is already solved by @navabpourn.

**Comment by MaSteinberg** [comment]
Yep, works - thanks!
