### ISSUE TITLE
As a data manager I would like to edit the "Terms and conditions" 

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#206]
A file refers to the "terms and Conditions" should exist inside the "content" folder in the tenant.
During registration, users should accept the content of this file. A data manager must have access to modify this file in the Tenant folder according to the project requirements.

**Comment by navabpourn** [comment]
**Describe the bug**
"Terms and Conditions" is not accessible via Tenants folders.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to Workspace\Tenants
2. Click on a Tenants folder
3. Click on Contents

**Expected behavior**
A file for "Terms and Conditions" should be available here.

**Actual behavior**
If I want to edit the content of the "Terms and Conditions", I have to edit an Index file under ~\Site\Views\TermsAndConditions

**Additional context**
The problem occurs when I replace the page in the next update. The changes will be gone.

**Comment by DavidBlaa** [comment]
tested in 2.12.2
