### ISSUE TITLE
Not registered email address could enter for the password recovery

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#210]
If I click on the "Forgot your password", I am able to enter an Email which is not registered in the BEXIS2 system. This email address does not receive a recovery password email.
It would be nice to inform the user about the wrong or not registered email address.

**Comment by sventhiel** [comment]
The rationale behind this behaviour is, to prevent users to sniff for email addresses from registered users.

**Comment by sventhiel** [comment]
After internal discussions, we decide to close this issue and keep going the same way. The reason is mentioned above.
