### ISSUE TITLE
Reset password confirmation contains not relevant message

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#211]
After resetting the forgotten password I am automatically logged in, but a message tells me "click here to log in". 
If I am logged in, I don't need to see this message. 

- If I have to see the confirmation message, the message could be like "click here to continue" and refers me to the first page. 
or 
- I should not be logged in. I am clicking on the link and refers to the login page.

![login8](https://user-images.githubusercontent.com/20185586/48848395-135bc180-eda4-11e8-8400-5a3c685b99df.jpg)

**Comment by navabpourn** [comment]
I found this issue on the Demo 2.12. But it is correctly not logged in while confirmation in the version that I downloaded from the BEXIS2 website as the latest version (2.12).

**Comment by sventhiel** [comment]
So to say it is solved?

**Comment by sventhiel** [comment]
Did you check it could update the status of this issue @navabpourn?

**Comment by navabpourn** [comment]
It is correct now. I am closing this issue :)
