### ISSUE TITLE
Download data structure template should be available after "save" only

### ISSUE THREAD

**Issue by romangerlach** [BEXIS2/Core#212]
issue received via email (22/11/2018): 

Im "Data Structure Edit" habe ich eine neue Data Structure kreiert und 4
Variablen Templates hinzugefügt.

Wenn ich dann auf "Download Excel Template" klicke, bevor ich explizit
auf "Save" oder "Save as" geklickt habe, erhalte ich ein leeres
Excel-Template. Recht verwirrend.

Statt diesem Verhalten würde ich vorschlagen, dass der "Excel Template"
Download erst verfügbar ist, nachdem die Data Structure gespeichert
wurde oder, dass eine Download des Templates vorab zu einem Speichern
der Data Structure führt (nicht ganz so schön).

**Comment by romangerlach** [comment]
solution: gray-out the download button until it is saved

**Comment by DavidBlaa** [comment]
@MaJoHo Did you work on that?

**Comment by DavidBlaa** [comment]
works fine
