### ISSUE TITLE
Error by clicking on tabs in manage parties

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#214]
**Describe the bug**
After updating from version 2.12.0 to 2.12.1 when I click on a tab in manage parties page, I see the error below.
See also #215 
I am able to edit and see parties in the tab "All".

![error-party](https://user-images.githubusercontent.com/20185586/49507018-db627d00-f87f-11e8-803b-4985b15b4efc.jpg)

**Comment by sventhiel** [comment]
Hi @navabpourn,

Please provide more information. You could use so called "Developer Tools" within your preferred web browser. Just keep track of the console and/or network calls you are doing. The tools will give you some additional information about the errors.

May we will provide an extra document for such workflow.

**Comment by navabpourn** [comment]
Hi @sventhiel,
Is it help more?

![error-party1](https://user-images.githubusercontent.com/20185586/49508905-3a29f580-f884-11e8-9141-353fd2852fe4.jpg)

**Comment by sventhiel** [comment]
Hi @navabpourn,
unfortunately not that much. Could you send me further information about/containing web.config, workspace folder (incl. partytypes.xml) and so on?

Best regards
Sven

**Comment by navabpourn** [comment]
Thank you @sventhiel for your reply.
I will send you an email.

Yours,
Nafiseh

**Comment by sventhiel** [comment]
Dear @navabpourn,
in the meantime, it seems that was fixed. Please look again at [BEXIS2 Demo](http://bexis2.vmguest.uni-jena.de/bam/Party/index).

**Comment by navabpourn** [comment]
Dear @sventhiel, this bug is fixed in my current version (2.12.3).

**Comment by sventhiel** [comment]
So then lets keep the status at least for the next tests. Afterwards, we can close it hopefully.

**Comment by DavidBlaa** [comment]
tested it in v6 and it seems to be fixed

**Comment by DavidBlaa** [comment]
But there's one more thing. @navabpourn 

some time ago we had the problem that your PartyType.xml was changed, but the table entries were not.

Please check the PartyType.xml in your workspace with the PartyCustomGridColumns
