### ISSUE TITLE
Current version does not show in the footer

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#216]
**Describe the bug**
The tooltip on the footer shows only "BEXIS" and it does not show the current version.

**To Reproduce**
1. Open http://bexis2.vmguest.uni-jena.de/
2. Drop the mouse on the BEXIS logo in footer.
3. Look at the opened tooltip. It is "BEXIS".

**Expected behavior**
The opened tooltip should be "BEXIS2.12.1".

**Screenshots**
![untitled](https://user-images.githubusercontent.com/20185586/49864241-5092fc80-fe02-11e8-9dcf-849e4ad45e76.png)

**Additional context**
I think it is controlled by the key "ApplicationVersion" inside the web.config. The value should be "2.12.1".

**Comment by sventhiel** [comment]
You are right. Thas information is comming from one key-value-pair inside the Web.config.

So you can configure it. The issue should be solved after entering a proper value.
