### ISSUE TITLE
Data does not download in the correct order

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#219]
**Describe the bug**
I have uploaded a dataset. The first column is ID, which begins with 1 and continues.
Sometimes, when I download the dataset, data rows are in inverse ordering. For example, if the data is from ID = 1 to ID = 10, the downloaded data is from ID = 10 to ID = 1. 
To solve this issue I sort data by ID and then download it. This confuses the normal user.

I did not find when exactly happens this problem.

**Comment by DavidBlaa** [comment]
i can't create this case. can you please show me some more screenshots and/or an application where this occ

**Comment by DavidBlaa** [comment]
can you please give me more information, otherwise I would move the bug to the next patch.

**Comment by navabpourn** [comment]
Dear @DavidBlaa I will write more details if I can reproduce this issue and I have more information.

**Comment by DavidBlaa** [comment]
we are in the process of finishing the version, the next patch will come soon, so i will postpone the task. so you still have time to clarify that.
