### ISSUE TITLE
Destruction of data when uploading a dataset containing empty cells

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#220]
**Describe the bug**
More data are added to the dataset after uploading.

**To Reproduce**
Please find the original file in your E-Mail box.

**Actual behavior**
As you see in the original file, the column of DEPTH has no data in its cells which are filled with "21" after uploading.

**Screenshots**
This is the original file:
![original](https://user-images.githubusercontent.com/20185586/50964593-f86a1b80-14cf-11e9-97cd-1e401071f3b2.jpg)

and it is the data after upload:
![original2](https://user-images.githubusercontent.com/20185586/50964594-f86a1b80-14cf-11e9-9769-6b3f9c270bc2.jpg)

**Comment by sventhiel** [comment]
Hi @navabpourn,

that is right - the issue is still open. No investigation from our site, yet. But we will check that, soon.

Best regards
Sven

**Comment by navabpourn** [comment]
Dear @DavidBlaa,

I could reproduce this issue also on the demo version.

Kind regards,
Nafiseh

**Comment by navabpourn** [comment]
It works fine in the test server on ports 2001 and 2002.
Thanks :)
