### ISSUE TITLE
Sorting of the time axis/id is mixed up

### ISSUE THREAD

**Issue by mguderle** [BEXIS2/Core#232]
A data set with 14400 rows was uploaded to the ATTO Data Portal.

The column TimeUTC in this data set is the time in seconds summed up starting from a specified point of time. 

It was noticed that a line was swapped here, which actually should be coming at the end of the data set.

 Row   TimeUTC
 7805    82819800
 7806    94678200
 7807    82821600

After checking the database, this mix-up is also appearing in the materialized view of this data set as well as in the datatubels. However, the order in the original file, which was uploaded is right.

**Comment by DavidBlaa** [comment]
I think this is fixed, but needs to be checked again.

Generally the problem was that the tuples were not in the correct order in the table. (order of the id's was not correct)

We have solved the problem by sorting the datatuples per id before.
