### ISSUE TITLE
Bug an issue in Attachment

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#249]
**Describe the bug**
1. The description is not saved
2. The size of the Description box changes badly

![description](https://user-images.githubusercontent.com/20185586/56805251-b9669880-6828-11e9-9a8e-15c8dab7b4b7.jpg)

**Instance**
 - SPP2089 instance
 - Version 2.12.2

**Comment by geofranzi** [comment]
**prevent resize of textarea**

```CSS
    max-width: 100%;
    min-width: 80%;
```

- [ ] I would also suggest to rename "Push" to "Submit".
- [ ] ...and if I have time I will fix the problem "Description" and "Files" is not in one line (Chrome/IE) FF is fine

**Comment by geofranzi** [comment]
The description is stored and shown on the infobox (tooltip). This could be improved in the future.
