### ISSUE TITLE
User Story 13: As a user I would like to filter & select primary data and download only the selected

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#25]
The System should have a filter for subsampling primary data in order to download these subsamples.

- [x] Reactivate the Filter/Sorting functions in the Grid
- [x] The Dataset Manager should be able to handle filtered/sorted query
- [x] Create Unit tests for Filter/Sorting functions in the Grid
- [x] Add a function to return the number of rows matching a filter expression.
- [x] Check all available filter options in the UI
- [x] Number of rows in the grid missmatches with the filtered result number
- [x] Downloaded primary data, filtered or not, includes one extra empty row at the end.

**Comment by navabpourn** [comment]
After filtering, the entire line number is not updated. Filtered out data is displayed as an empty line.

**Comment by DavidBlaa** [comment]
Hi @javadch 
this is for you :D

The Datasetmanager has a function to load datatuples from the database and convert it to a datatable.
In addition, the filter options now come back.
To display the data in a table, the system needs a function that counts the rows from the filtered result.

**Comment by javadch** [comment]
Added a function `RowCount` to the `DatasetManager` class. It has two overloads, one accepts a `FilterExpression`.

**Comment by navabpourn** [comment]
@DavidBlaa  One extra empty row is added to the download file.
