### ISSUE TITLE
Download dataset in text format

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#250]
**Describe the bug**
Downloaded primary data in the different formats have the same content. They are all tab separated. 

**Expected behavior**
The data in the comma-separated format should separate by a comma, and the data in TXT format should separate by space.

**Instance**
 - SPP2089 instance
 - Version 2.12.2

**Comment by DavidBlaa** [comment]
in txt files, tabs are used as seprators because space is one of the most vulnerable characters when reading and can easily lead to errors.

**Comment by DavidBlaa** [comment]
test case is in the test quality tool
