### ISSUE TITLE
Defined primary key is gone if the selection is not unique

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#254]
**User lost the selection**
During the upload process, when I would like to update an existing dataset, I have chosen the update method. I selected a set of variables as a key for an update, but the key was not unique. The system warned me with a red message "Selection is not unique" and my selections are gone.
The user needs to remember the non-unique selection.

**Describe the solution you'd like**
The selected variables and the warning message should stay until the user changes the selection.

**Describe alternatives you've considered**
As an alternative, the system could show a pop-up warning message.

**Screenshot**
![SharedScreenshot](https://user-images.githubusercontent.com/20185586/57364475-91115f00-7183-11e9-924d-a11eb217295e.jpg)

**Comment by sventhiel** [comment]
Hej @navabpourn,

I am really sorry - there was no communication about that issue for a long time. Do you know if it is still valid?


Cheers, Sven

**Comment by navabpourn** [comment]
Dear @sventhiel, 
Thanks for your response.
Yes, it is still valid. The selection is gone when I get the error message.

**Comment by DavidBlaa** [comment]
in the new upload process the  primary key is set when the structure is set, no need to define it during the upload process
