### ISSUE TITLE
A table to store the information of variable templates in the database is missing

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#255]
Hi,
I wanted to edit variable templates, and in that way, I found a problem.

**Describe the problem**
Inside the database, there is not a table to store information of variable templates. I mean there is not a table to store the name, short name, unit and description of variable templates. 
This makes problems.

**First:** 
There is no way to edit a variable template through the database. 
For example, you made a mistake by the typo in the description. Once a data structure uses a variable based on this variable template there is no way to edit it.

**Second:** 
The table of "variables" in the database store all information about variables. These are variables based on variable templates. 
"dataattributeref" in this table refers to the variable's id. I expected it to be a foreign key in another table, but I could not find a table about data attributes.

Now go through this way:

1. Create a new variable template and call it "TestVariableTemplate"
2. Create a new data structure and add this variable template to it.
3. Change the name of this variable to "TestVariable" (optional)
4. Create a new dataset and use this data structure for it.
5. Upload data to this dataset.
5. Check that you cannot edit the "TestVariableTemplate"
6. From the database, open the "variable" table
7. delete the line of "TestVariable"
8. Go back to the data structure. "TestVariable" is deleted from the data structure. Then, this is not the original data structure. If you check the dataset, you find that the variable is also missed in its data structure. 
9. You are now able to delete the "TestVariableTemplate" 

**Solution"
I am not an expert in database design, but I suggest creating a table "dataattributes" to store all information of variable templates. It should have a column for "unitref".
In the table "variables" you don't need column "unitref". "dataattributeref" in this table refers to the ids of variable templates. 
Later when you want to create an Excel template or download dataset with Excel template, the information about units should get from the table " dataattributes". 

Yours,
Nafiseh

**Comment by geofranzi** [comment]
The table is called "datacontainer" and holds the information you are looking for.
