### ISSUE TITLE
System transforms "<" to "&lt;"

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#256]
**Describe the bug**
I uploaded data contains the character "<". System transfer this character to the "&lt;".

**Screenshots**
Original data:
![SharedScreenshot1](https://user-images.githubusercontent.com/20185586/57454125-6c42e780-7268-11e9-93c3-b6d32680320c.jpg)

uploaded data:
![SharedScreenshot2](https://user-images.githubusercontent.com/20185586/57454181-85e42f00-7268-11e9-9881-f1cbb97ab5f3.jpg)

**System:**
 - Instance: SPP 2089
 - Version: 2.12.3
 - Browser: Chrome

**Comment by geofranzi** [comment]
Tested with 2.14. Works fine.
