### ISSUE TITLE
Mapping JavaScript bug

### ISSUE THREAD

**Issue by AntonioNoack** [BEXIS2/Core#265]
**Describe the bug**
when clicking on Create to create the mapping connection, a connection-is-undefined-exception is thrown in JavaScript (bexis.dim.mapping.js:388)

**To Reproduce**
1. Go to http://bexis2.vmguest.uni-jena.de/dcm/ManageMetadataStructure/Index
2. Click on 'Mapping to system'
3. Click on one entry on the left and one on the right (bracket arrows to the center) to send them to the center
3. Click on 'Create'
4. See the error in developer console 

**Expected behavior**
The elements should be visually connected

**Actual behavior**
Uncaught TypeError: Cannot read property 'connections' of undefined
    at saveMapping (bexis.dim.mapping.js:388)
    at HTMLButtonElement.onclick (Mapping?sourceId=31&targetId=0&sourceType=MetadataStructure&targetType=System&position=Target:1129)
No connection happens, nothing happens visually

**Screenshots**
![Screenshot (4)](https://user-images.githubusercontent.com/20659579/58426502-6571ee00-8038-11e9-8977-623346d962d3.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome 74.0.3729.169 (Offizieller Build) (64-Bit)
 - Version: http://bexis2.vmguest.uni-jena.de, I don't know where I'd find the version of the instance

**Additional context**
I don't need this personally, just wanted to test it.

**Comment by DavidBlaa** [comment]
not fixed

@Hamdi1992 we need to check it for the next release. may you send a pull request
