### ISSUE TITLE
As a user I would like to see the full name in tab dataset permission, instead the username

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#269]
In view details of a dataset, in the tab Dataset Permission, a user sees the usernames of other users. Users may have chosen the fantasy usernames. Therefore, the full names must be listed here.
- [x] change account to the user name in dataset permission view
- [x] check performance
- [x] remove id column in dataset permission view
- [x] define user name directly (instead of indirect via "isMain", which is the current implementation) - fine for now. no urgent need to change.
- [x] change account to user name in administration views
- [x] add account name to feature permission view

**Comment by geofranzi** [comment]
performance checked with the user accounts from the exploratories. It seems it is not an issue.

definition via the "isMain" attribute is fine for now.
