### ISSUE TITLE
User Story 15: As a user I would like to have an info button next to each field in the metadata

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#27]
have an info button next to each field in the metadata so that it is obvious where I have to go for detailed information on how to fill in the respective metadata field.

- [x] Update UI in Metadata Form

**Comment by navabpourn** [comment]
Info buttons are missed close to the following items:
Technical Contact -> Email and Address
ContentContact -> Email and Address
Telephone Number -> Device
Addresses -> Address

**Comment by DavidBlaa** [comment]
In the xsd of ABCD, there is no description for the nodes you asking for.
e.g. MicroAgent is the type for Technical Contact & Content Contact:

![image](https://user-images.githubusercontent.com/19665289/41093655-30cc9a7c-6a4c-11e8-9a3c-aecd8a28ee0c.png)

**Comment by navabpourn** [comment]
OK, it's fine. Then you can close this issue :)
