### ISSUE TITLE
Integrate Multimedia Module

### ISSUE THREAD

**Issue by MaJoHo** [BEXIS2/Core#281]
To have a nicer view for unstructured date the MMM should becom part of the core modules.

**Comment by MaJoHo** [comment]
I added the MMM

to use it add this line to the Module.Catalog.xml

```xml
<Module id="mmm" status="active" order="8" />
```
to turn it on/off you can use that key in the web.config

```xml
<!--
This flag truns on/off the Multimedia Module.
-->
<add key="useMultimediaModule" value="true" />
```
And add the attached folder to the Workspace
[Workspace.zip](https://github.com/BEXIS2/Core/files/3411326/Workspace.zip)

**Comment by DavidBlaa** [comment]
i should be tested from other persons

**Comment by DavidBlaa** [comment]
I can't see any merge to dev either. Has it been done yet?

**Comment by DavidBlaa** [comment]
test case is in the test quality tool
