### ISSUE TITLE
Public features not showing up in Menue

### ISSUE THREAD

**Issue by MaJoHo** [BEXIS2/Core#288]
If features are set to public they are not shown in the menue for not loged in users 

1. Go to feature pemissions
2. set some fetures to public
3. log out

all public features should be visible for not loged in users

 - windows 10 edu 1903
 - Firefox Quantum 68.0.1

**Comment by MaJoHo** [comment]
Public features are still not visible in menu, if not loged in . 

dev branch from 04.09.2019

**Comment by DavidBlaa** [comment]
if i run my dev (its sync with github) it seems to work.

Search is public
![image](https://user-images.githubusercontent.com/19665289/64424196-ac946400-d0a8-11e9-8e18-27c3f15b8427.png)

![image](https://user-images.githubusercontent.com/19665289/64424240-cfbf1380-d0a8-11e9-9e6f-ae0cc32053ca.png)

**please check your sync status again. it seems like you don't have all the changes.**

**Comment by DavidBlaa** [comment]
test case is in the test quality tool
