### ISSUE TITLE
User Story 18: As a user, I want to automatically determine and apply rights on a dataset during dataset creation.

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#29]
need a fixed field in metadata who are owners/PI and got rights on dataset (this can be one solution but not necessarily)

- [x] A method to extract required information from the dataset’s metadata and register them in the dataset’s permissions is needed. (@DavidBlaa; 2 days)
- [x] There should be a step in metadata validation that checks for existence of these required elements/attributes (@DavidBlaa; 2 days)
- [x] There should be a method to resolve the extracted entries to users/persons.  (@DavidBlaa; 1 day)
- [x] One possible solution would be to integrate the party package into the security system (@sventhiel , Masoud; 2w3d):

**Comment by navabpourn** [comment]
If I have well understood, when I create a dataset and set David as Technical Contact or Content Contact, he should get rights (read, download, ...) for this dataset. In the Bexis2 RC1 I created dataset#9 with that setting, but the rights did not set for David.

**Comment by navabpourn** [comment]
The right to read is missing.
