### ISSUE TITLE
Typo error in the installation manual

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#297]
In the first page, in the Acknowledgment part, a "G" is missing.
It could be copied in other user manuals. I did not check.

![SharedScreenshot1](https://user-images.githubusercontent.com/20185586/64242000-0c520a00-cf05-11e9-8da4-d81cbf59b41a.jpg)

**Comment by geofranzi** [comment]
The word documents are no longer maintained. The error was inside from the beginning.
