### ISSUE TITLE
Add version change type and what (metadata / data) to each action which results in change of version

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#306]
- [x] add version change type and what (metadata / data)
- [x] adjust selection list in UI
- [x] remove "create" for old datasets
- [x] attachment delete not working

per datasetversion there is a m_actiontype and m_performer:
use it.

like m_actiontype is a enum like create,edit....
m_performer = metadata,data,file

**Comment by DavidBlaa** [comment]
it works
