### ISSUE TITLE
Create Party - Fail [D6]

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#311]
Creating an organization is not always error-free. It works sometimes.

<br>

![null](<blob:https://bexis2.testquality.com/ed0badbb-73e7-4232-bad5-6eb76f5ed8ab>)

**Comment by navabpourn** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D6. Do not remove or edit.` [D6](https://bexis2.testquality.com/project/8555/result/1470777/defect/5170)

**Comment by DavidBlaa** [comment]
there was a seed data problem, why the grid columns for the parties were not created. therefore there was an error message at call, which led back to a grid
