### ISSUE TITLE
Delete Releationship - Fail [D7]

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#312]
An error occurred while deleting a relationship [Person, Project]. Regardless of the error, the relation is deleted.

<br>

![null](<blob:https://bexis2.testquality.com/aba373a5-8f45-4e69-9e01-d0bfc630923a>)

**Comment by navabpourn** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D7. Do not remove or edit.` [D7](https://bexis2.testquality.com/project/8555/result/1470783/defect/5171)

**Comment by DavidBlaa** [comment]
there was a seed data problem, why the grid columns for the parties were not created. therefore there was an error message at call, which led back to a grid
