### ISSUE TITLE
Delete Party - Fail [D8]

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#313]
Error while deleting a party

<br>

![null](<blob:https://bexis2.testquality.com/261cddfa-1851-43eb-a181-0e2d82603570>)<br>

**Comment by navabpourn** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D8. Do not remove or edit.` [D8](https://bexis2.testquality.com/project/8555/result/1470779/defect/5172)

**Comment by DavidBlaa** [comment]
there was a seed data problem, why the grid columns for the parties were not created. therefore there was an error message at call, which led back to a grid
