### ISSUE TITLE
Delete Party - Fail [D10]

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#315]
The party is deleted, but the system shows the error message.

<br>

![null](<blob:https://bexis2.testquality.com/6561e869-4b5e-46b3-aaf7-c216a335b237>)<br>

**Comment by navabpourn** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D10. Do not remove or edit.` [D10](https://bexis2.testquality.com/project/8555/result/1471590/defect/5180)

**Comment by DavidBlaa** [comment]
there was a seed data problem, weshlab the gridcolumns for the parties were not created. therefore there was an error message at call which returned to a grid

**Comment by DavidBlaa** [comment]
there was a seed data problem, why the grid columns for the parties were not created. therefore there was an error message at call, which led back to a grid
