### ISSUE TITLE
Delete Releationship - Fail [D13]

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#318]
I am not allowed to delete a relationship. The error message says at least one relationship is required, but I have more than one.

<br>

![null](<blob:https://bexis2.testquality.com/afa167d8-8b9d-49fe-904e-cb55d551b41d>)

**Comment by navabpourn** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D13. Do not remove or edit.` [D13](https://bexis2.testquality.com/project/8555/result/1471594/defect/5196)

**Comment by DavidBlaa** [comment]
fixed
