### ISSUE TITLE
User Story 4: As a user I would like to upload additional support files to a dataset 

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#32]
Need a functionality to upload supporting file to metadata.
( implemented as a dataset descriptors) 

- [x] There should be a way to manage files to a specific dataset version - metadata (@MaJoHo ; 2 days)
- [x] It should be possible that when using the dataset viewer the user is able to simply upload new files, delete the current ones, etc. Without needing to go through the dataset upload or easy upload workflows. (@MaJoHo ; 2 days)

**Comment by javadch** [comment]
@DavidBlaa can you share the URL of the repository you said has implemented a similar solution?

**Comment by DavidBlaa** [comment]
https://github.com/mguderle/Core

it is in the ato module.
you need to have a xml document "Documentation.xml" in the workspace.

here you see the simple structure of it.
![capture](https://user-images.githubusercontent.com/19665289/40534795-7745682a-6007-11e8-962c-ca6de61255a7.PNG)
