### ISSUE TITLE
Upload Data - Fail [D15]

### ISSUE THREAD

**Issue by EleonoraPetzold** [BEXIS2/Core#323]
**Step 1 Pass**

Navigate to Collect/Upload Data and click the tabular button

**Step 2 Pass**

Click on the Select button to upload the data file

**Step 3 Pass**

Select a valid file and click on the Next button.

**Step 4 Pass**

Select an existing dataset from the select drop-down list to attach your file with.

**Step 5 Pass**

Click Next Button

**Step 6 Pass**

Click Next Button

**Step 7 Pass**

Click on the Validate button.

**Step 8 Pass**

Click on the Next button.

**Step 9 Fail**

Click Finish Button

**Comment by EleonoraPetzold** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D15. Do not remove or edit.` [D15](https://bexis2.testquality.com/project/8555/result/1471516/defect/5209)

**Comment by EleonoraPetzold** [comment]
The system only upload one data row from the file. I did it twice and again only one row

**Comment by DavidBlaa** [comment]
the problem were the deactivated macros in the excel template
