### ISSUE TITLE
User Story 6: As a data manager, I want an extra page for public data

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#33]
metadata info differs from internal data.

Having a public page that shows marked datasets to anonymous users.

- [x] the app would have two URLs for public datasets’ search and the current traditional search. The first one queries the search provider only for the datasets that are marked as public. (@DavidBlaa)
- [x] Dataset owners/managers decide which dataset is public. This flag is considered during indexing and search. (@sventhiel)
- [x] There would be configurable landing page that is by default on the current search page, but admins can change it to the public search for anonymous users.(@javadch)

**Comment by javadch** [comment]
All the tasks are done. 
Currently, when an admin sets/unsets one or more datasets to/from `public`, s/he should reindex the search.
I would suggest that @sventhiel integrates the reindexing feature into the function that controls the datasets' states so that the search index store remains in sync.
