### ISSUE TITLE
Dashboard: Rename to "My Data"

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#333]
The current name is misleading and raises wrong expectations.

**Comment by geofranzi** [comment]
Each instance can handle individually. The Exploratories will name it: "My Data".

**Comment by geofranzi** [comment]
Discuss again.

**Comment by aostrow** [comment]
@geofranzi :  bei uns steht nun wie gewünscht das "My Data" da. Ist das nur bei uns angepasst oder schon allg. im Core so? Kann der issue zugemacht werden?

**Comment by geofranzi** [comment]
nur bei uns

**Comment by geofranzi** [comment]
Renaming accepted by data curator group. Ok for 2.15 (not before).
