### ISSUE TITLE
User Story 14: As a user I would like to upload .xlsx files as well

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#34]
- [x] Update the default tenant’s manifest to all TSV, and XLSX! (@DavidBlaa)
- [x] Advance the Excel reader to support xlsx (@DavidBlaa)
- [x] Support for CSV and TSV file extensions (@DavidBlaa)
- [x] Advance the Upload Wizard UI to accept the supported file formats/ extensions. (@DavidBlaa)

**Comment by navabpourn** [comment]
Test review:
An xslx file selected. After click on the Next button comes this warning: Cannot access FileStream on server.

**Comment by navabpourn** [comment]
@DavidBlaa Upload is not successful. 
It does not depend on the file format. The loading time does not end.
