### ISSUE TITLE
Download Package - Fail [D24]

### ISSUE THREAD

**Issue by CFuerstenau** [BEXIS2/Core#341]
**Step 1 Fail**

Navigate to the Dataset View and select the primary data tab

**Step 2 Fail**

download the full dataset with any format you like

**Step 3 Fail**

compare zip with dataset

**Comment by CFuerstenau** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D24. Do not remove or edit.` [D24](https://bexis2.testquality.com/project/8555/result/1471638/defect/5292)

**Comment by DavidBlaa** [comment]
test in the next release version, if its happen again, open it again
