### ISSUE TITLE
Enter long text in a text input - Fail [D25]

### ISSUE THREAD

**Issue by EleonoraPetzold** [BEXIS2/Core#342]
long text overlap after save in the" view view

**Comment by EleonoraPetzold** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D25. Do not remove or edit.` [D25](https://bexis2.testquality.com/project/8555/result/1471533/defect/5293)

**Comment by EleonoraPetzold** [comment]
![image](https://user-images.githubusercontent.com/42029171/66042461-c6e12680-e51c-11e9-9aa7-3494569774af.png)

**Comment by geofranzi** [comment]
I will check if this is related to my recent changes ...
