### ISSUE TITLE
User Story 21: As a user I would like to have a definition of missing values

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#35]
have a definition of missing values, which is also recognized by the database.

**Comment by MaJoHo** [comment]
to define a missing value we need to store
- id
- displayname (e.g. NA)
- placeholder (e.g. 2147483647)
- description (e.g. Value not available for any reason)
- variableref (to get datatype ...)

**Comment by DavidBlaa** [comment]
using missing values:

- [ ] validation during the upload process
- [ ] display data in the ui
- [ ] download

**Comment by DavidBlaa** [comment]
its done and tested well
