### ISSUE TITLE
User Story 12: As a user I would like to download a zip-file incl. metadata, primary data, data structure

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#36]
- [x] There should be a single button in dataset viewer to all to select the content (primary, metadata, attachments, etc.) and the format (CSV, XLS, etc.), prepare the zip file and download it.(@DavidBlaa)
- [x] It would be great if a mini viewer for metadata and data structure is in the zip package. The viewer allows a user to see the metadata while offline. It can be an HTML version of the metadata, or any other method (e.g PDF).(@DavidBlaa)
- [x] Tests

- [x] The title of the button is not user-friendly (Download with Excel)! Add more informations.
- [x] The function does not work for some Datasets (e.g. Id=19 or Id=100) by clicking on the button, But it works when I click on special function (e.g. Download with CSV).
- [x] I select "Download with CSV" and the output includes Excel, Txt and CSV. Then why I have different options?

**Comment by navabpourn** [comment]
Test review:
- The title of the button is not user-friendly (Download with Excel)!
- The function does not work for some Datasets (e.g. Id=19 or Id=100) by clicking on the button, But it works when I click on special function (e.g. Download with CSV).
- I select "Download with CSV" and the output includes Excel, Txt and CSV. Then why I have different options?

**Comment by navabpourn** [comment]
Download with Excel must test again after merging.
