### ISSUE TITLE
Dashboard/ Requests

### ISSUE THREAD

**Issue by mguderle** [BEXIS2/Core#366]
On colleague mentioned a bug/request of the Dashboard:
"It seems that the sorting of the different columns in the Dashboard view/Decisions does not work.
Also, if possible, it would be practical to have an additional column containing the date of the request."

Indeed, the request status is shown by 0 and/or 1 and the filter asks for "Open, Accepted, Rejected", so the filter function does not work.

Is there a possibility to include the request date in the Request/Decision taps as well as the user name?

**Comment by geofranzi** [comment]
Date will be added under: https://github.com/BEXIS2/Core/issues/532
Filter/sort will be solved by replacing telerik with data tables
