### ISSUE TITLE
User Story 17: As a data manager I would like to provide documents through the UI 

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#37]
store documents like data policy, introductions & How To’s on the Platform. Configurable page for documents. (e.g. The place should be the first page a user is directed after logging in.)
Check “file upload” developed by Explos

- [x] A mechanism to upload a file (@javadch)
- [x] A mechanism to maintain the files, titles, description and their folder structure (@javadch)
- [x] A mechanism to list the files 
- [x] A mechanism to download a file or folder (folder will be zipped)
- [x] A mechanism to delete a file or folder
- [x] A mechanism to rename a file or folder

**Comment by DavidBlaa** [comment]
https://github.com/mguderle/Core

it is in the ato module.
you need to have a xml document "Documentation.xml" in the workspace.

here you see the simple structure of it.

![capture](https://user-images.githubusercontent.com/19665289/40651602-69f670ba-6336-11e8-8be9-f3d25c2a5812.PNG)

**Comment by javadch** [comment]
I developed the file manager and the required controller in the SAM module. Also, the XML file for maintaining the description, display name, etc. are in place. An initial UI is also developed and working.
@matparsa will take over the issue and further develops the remaining items.

**Comment by matparsa** [comment]
All the features were added. Another page for viewing documents for end-users was added and is accessible via /SAM/Files/FileList

**Comment by javadch** [comment]
@matparsa please update us on the final status of this issue.

**Comment by navabpourn** [comment]
I can not test it because I have no access to these features. See issue #165

**Comment by navabpourn** [comment]
The user cannot edit the folder name.
