### ISSUE TITLE
As developer I need to gain user registration date

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#39]

**Comment by sventhiel** [comment]
Currently, there is no way to get that information via UI. It is just part of the backend logic. But I am going to add some information into the ui.

**Comment by navabpourn** [comment]
As a developer, not a user. No need in UI. It is enough only inside the database.

**Comment by DavidBlaa** [comment]
it seem that there is a registration date in the users table.

![image](https://user-images.githubusercontent.com/19665289/44571666-b4c18000-a781-11e8-9ef0-5f4dc7817c8d.png)

so i will close that issue.
