### ISSUE TITLE
As a data manager I need a user manual manager

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#394]
It is a demand by Mark Frenzel.

**Is your feature request related to a problem? Please describe.**
The problem is that a data manager provides specific user manuals for an instance of BEXIS 2. It would be nice if the specific user manuals are accessible via BEXIS 2 application.

**Describe the solution you'd like**
Mark Frenzel suggests an editable link in BEXIS 2 which refers to e.g. google docs or anywhere else where the data manager has uploaded all specific manuals there.
My suggestion is to show PDF files instead of HTML page. PDF files could be placed in Tanent folder, includes specific user manuals.

**Comment by geofranzi** [comment]
Manual / How-to link can be set now in the settings of each module.
