### ISSUE TITLE
User Story 19: As a user, I want to delegate/determine the responsibility of a dataset during metadata creation.

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#40]
need a fixed field in metadata who is contact, and gets email.

- [ ] The metadata UI (entry/editing) should provide enough information and interaction so that the user is able to select which person is assigned to which role(s).
- [x] It needs the solution of US2 #31, and US18 #29  (test case)
- [x] It relies on party type and relationship type traversal from party package for the time of metadata entry and responsibility assignment. 
- [x] This information can be used for the notification system. 
- [x] The notification system can have its own configuration, so that the selected roles get notified on a specific action. These roles are also obtained from the party package.

**Comment by DavidBlaa** [comment]
available in r2.12 rc2

**Comment by navabpourn** [comment]
The right to read is missing for the determined owner.
