### ISSUE TITLE
User Story 8: As a user I would like to import additional data models in the easy (automatic) upload 

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#41]
We need to auto/semi map data attribute to existing defined data attributes in BEXIS

- [ ] The mechanism should allow for selection of headers and tuples in different places of a sheet as well as different orientations.
- [ ] It should be possible to select multiple areas as data
- [ ] It should be possible to select the deaders in one sheet and the data in another
- [ ] It should be possible to select multiple sheets as the data

**Comment by geofranzi** [comment]
The new upload workflow #824 replacing easy upload will not implement fully flexible access of the data. Data should be somehow structured before. The selection of header and data will be similar to now. Too much-allowed flexibility would bring more potential for errors.
