### ISSUE TITLE
Dataset View - Order of Versions

### ISSUE THREAD

**Issue by sventhiel** [BEXIS2/Core#431]
**Is your feature request related to a problem? Please describe.**
Currently, the versions of a dataset are listed in ascending order.

**Describe the solution you'd like**
The more intuitive way would be, that they are sorted in descending order.

**Describe alternatives you've considered**
Instead of calling "OrderBy", we should call "DescendingOrderBy".

**Comment by geofranzi** [comment]
not working ... order by VersionID also have no effect ....
