### ISSUE TITLE
UI improvements DataStructureEdit View

### ISSUE THREAD

**Issue by MaJoHo** [BEXIS2/Core#438]
- [x] Show a short description of Variables/Attributes in the collapsed state.
- [x] Have an empty variable description when adding it to Data Structure.
- [x] Fix line wrapping with long descriptions
- [x] Replace variable ID with column index
- [x] Highlight better "Filter"
- [x] Reorder Filter entries: Units first

**Comment by CFuerstenau** [comment]
- [ ] use unit abbreviations (m) instead of description (meter)

- [ ] list only units corresponding to the variable/dimention, e.g  for length -> m, km, cm not m³, ...

**Comment by MaJoHo** [comment]
for the secound point please check your dimentions
