### ISSUE TITLE
DB update script incomplete

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#443]
- [x] add column variables.missingvalue -> not needed
- [x] Alter table [if not exists] <- does not work

**Comment by MaJoHo** [comment]
soory i did not build the update skript

**Comment by MaJoHo** [comment]
i just check my just created DB and there is no variables.missingvalue column. It is also not needed if i remember right.

So please schow me the the problem in die next days.

**Comment by DavidBlaa** [comment]
thanks for the hints, the script will be updated with the next release.
