### ISSUE TITLE
Validation of files with constraints during upload fails

### ISSUE THREAD

**Issue by aostrow** [BEXIS2/Core#446]
- Validation during upload of a file (append data) fails if the self-defined contraint does not match an value
- no error message appears, just the validate button appears again
- click on next button says "validation failed"

- scenario: attribute plot_id with a list of plotids, file upload with new values to plotid column fails

![B2-upload-03](https://user-images.githubusercontent.com/26480843/72842292-58c19a80-3c98-11ea-8226-daecaea0fa0e.png)

**Comment by geofranzi** [comment]
Error messages have been improved and show now more details (see #676 ).
