### ISSUE TITLE
Missing sync after file append

### ISSUE THREAD

**Issue by aostrow** [BEXIS2/Core#447]
File was uploaded and version info was also shown in primary data view but new data was not there. After manual execution of admin panel - manage datasets - sync it appeared.

needed: automatic sync after data update

**Comment by geofranzi** [comment]
There is an error: {"Input string was not in a correct format."} MaterializedViewHelper.cs L 225 (Refresh)

**Comment by geofranzi** [comment]
- [ ] check error handling failed sync (maybe change mat view and update datasets to enforce an error)

**Comment by geofranzi** [comment]
linked to general error handling during data upload
