### ISSUE TITLE
Dataset links: goto dataset should open in new tab

### ISSUE THREAD

**Issue by aostrow** [BEXIS2/Core#449]
in dataset view in the Links tab the goto link opens in the same tab

expected: should open new tab

**Comment by geofranzi** [comment]
It is possible via right mouse click.  I think to avoid to open too many new windows unwanted we should keep it as it is.

**Comment by aostrow** [comment]
objection: should have the same behavior as a click on a symbol in search results (=open in new tab)

**Comment by geofranzi** [comment]
Ok, I will add to the buttons, but not to the linked title
