### ISSUE TITLE
Datastructure View: Link to data structure

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#452]
![image](https://user-images.githubusercontent.com/15946467/72901128-768b1000-3d29-11ea-98bc-7cd6bf1d3a86.png)

Add a link to data structure edit view, if the person has the permission. Otherwise, you need to find it, which could be very difficult with the automatically generated Data structure names from the easy upload.

**Comment by MaJoHo** [comment]
is not my module but should not to cmplicated i can have a look
