### ISSUE TITLE
Some download options do not work

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#461]
maybe related to my test data

![image](https://user-images.githubusercontent.com/15946467/73203827-1982c600-413e-11ea-8eb0-7db537711688.png)

my test data:
![image](https://user-images.githubusercontent.com/15946467/73203885-3b7c4880-413e-11ea-869e-d8945e779cd1.png)

**Comment by geofranzi** [comment]
It tries to find a path, which only exists where the dataset was created. It seems to absolute path is saved instead of relativ

Could not find a part of the path 'C:\[...our server path..] Workspace\Modules\DIM\MappingFile_intern_New-BE-MetadataSchema_to_extern_schema_explos_bexis2.xml'.

**Comment by geofranzi** [comment]
![image](https://user-images.githubusercontent.com/15946467/73926715-597d4200-48d0-11ea-970c-60d9c18a613c.png)

**Comment by DavidBlaa** [comment]
can you please check in your code if the paths are saved completely? When I look at the code of the schema import and the seeddata (e.g. ABCD Schema), I do not see complete paths to the mapping files.

![metadataschema](https://user-images.githubusercontent.com/19665289/74907240-4760d080-53b3-11ea-8180-907e355d61a3.JPG)

**Comment by geofranzi** [comment]
Hm, maybe it's introduced by accident during our migration process. I will check our code.

**Comment by geofranzi** [comment]
related to migration
