### ISSUE TITLE
Delete datatupels not working during import/migration

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#466]
How do we want to deal with it? (BE1 ID 6241)

23503: Aktualisieren oder Löschen in Tabelle »datatuples« verletzt Fremdschlüssel-Constraint »fk8a686099425de87a« von Tabelle »datatupleversions«
Description: could not delete: [BExIS.Dlm.Entities.Data.DataTuple#37249019][SQL: DELETE FROM DataTuples WHERE Id = ? AND VersionNo = ?]

Exception Details: Npgsql.PostgresException: 23503: Aktualisieren oder Löschen in Tabelle »datatuples« verletzt Fremdschlüssel-Constraint »fk8a686099425de87a« von Tabelle »datatupleversions«

**Comment by DavidBlaa** [comment]
no issue anymore
