### ISSUE TITLE
Version Information

### ISSUE THREAD

**Issue by sventhiel** [BEXIS2/Core#475]
**Describe the solution you'd like**
Whenever a BEXIS2 instance gets updated, three parts of the application may be affected:
- Site
- Workspace
- Database
To ease the update procedure and maintenance/support, there should be the information about the version each of that parts is running on.

**Describe alternatives you've considered**
NA

**Additional context**
Currently, it is quite hard to support BEXIS2 instances without specific information about the version of the system.

**Comment by sventhiel** [comment]
Actually, the changes are inside branch #475, and need to be merged.

**Comment by DavidBlaa** [comment]
fixed and tested
