### ISSUE TITLE
Display missing values in primary data view and download - strange behavior 

### ISSUE THREAD

**Issue by EleonoraPetzold** [BEXIS2/Core#484]
Bei der Anzeige der missing values passiert etwas komisches. Manchmal wird nicht der Display name angezeigt. 
Auf dem server ist es eine andere Variable als beim lokalen debug.

Beides String Variablen

Server:
![image](https://user-images.githubusercontent.com/42029171/75451000-131b8000-5970-11ea-8c81-e046669c6370.png)

Lokal:

![image](https://user-images.githubusercontent.com/42029171/75451048-229ac900-5970-11ea-867d-0afc5d0c6a9b.png)

**Comment by DavidBlaa** [comment]
kann es sein, das die Datei wo die Misisng Values definiert sind, einfach nicht existiert?

check bitte die rpm.settings.xml im workspace

**Comment by EleonoraPetzold** [comment]
In dem Datensatz gibt es viele missing values und es funktioniert bei den meisten Variablen. In der DB steht alles korrekt und im debug bei holen der displaynames und placeholder sah es auch gut aus. Unsere Vermutung war das bei rendern vlt was schief geht. 

 rpm.settings.xml im workspace steht was drin zu missing values, was soll ich da genau checken?
