### ISSUE TITLE
Remove js-alerts from Search

### ISSUE THREAD

**Issue by aostrow** [BEXIS2/Core#485]
Löschen? 
Oder mit sinnvolleren Sachen füllen. Manche sagen nur "OK".

**Comment by geofranzi** [comment]
Welche alerts, wie sehen die aus, wann kommen die ...

**Comment by aostrow** [comment]
js alerts.
wie alerts halt. s.o. steht bspw. "OK" drin.
manchmal halt. nicht reproduzierbar.

**Comment by sventhiel** [comment]
Hej,

unfortunately, I can't find such alerts (at least that are still active). Within the system there are a lot of alerts that are not active anymore (commented out).

I took a look into you fork, but also wasn's able to find anything. Even if it is not reproducable, may you could provide some additional information on the next time it happens?

Best regards
Sven

**Comment by geofranzi** [comment]
no new reports for reproduction on this issue so I will close
