### ISSUE TITLE
Search: "more" window has content + render problems 

### ISSUE THREAD

**Issue by aostrow** [BEXIS2/Core#487]
first cklick is ok:
![image](https://user-images.githubusercontent.com/26480843/75525796-c9cf3d00-5a10-11ea-976b-d7c86b744da2.png)

- if I choose 5, then click Breadcrump or more again
- now content is missing + window is rendered weird
![image](https://user-images.githubusercontent.com/26480843/75525920-07cc6100-5a11-11ea-897e-2a7839647163.png)

- if I click "none" and reopen the more window
- content is ok, but rendering weird
![image](https://user-images.githubusercontent.com/26480843/75526014-3813ff80-5a11-11ea-8c83-d16e5400a6c2.png)

**Comment by geofranzi** [comment]
looks like a Telerik-related JS problem. It will / can not be fixed in the current version.
