### ISSUE TITLE
Index out of range exception while finishing the easy upload process.

### ISSUE THREAD

**Issue by Hamdi1992** [BEXIS2/Core#488]
**Describe the bug**
Error While finishing the upload , but in specific case.

**To Reproduce**

we suppose dataset to be uploaded through easy upload : 
[variable1 , variable2 , variable3 , variable4]
[  val1-1   ,   val1-2  ,  val1-3     ,   Empty     ]
[  val2-1   ,   val2-2  ,  val2-3     ,   Empty     ]
[  val3-1   ,   val3-2  ,  val3-3     ,   Empty     ]
[  val4-1   ,   val4-2  ,  val4-3     ,   Empty     ]

i select header area (variable2, variable3) and its following data (val1-2, val1-3, val2-2, val2-3, etc)

**Expected behavior**
dataset to be uploaded and redirected to the metadata view of the dataset

**Actual behavior**
Error : "An error occured during the upload. Please try again later. If this problem keeps occuring, please contact your administrator"

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser : chrome

**Comment by Hamdi1992** [comment]
BExIS.IO.Transform.Input.ExcelReader.cs
`        private List<string> RowToList(Row r)
        {
            string[] rowAsStringArray = new string[numOfColumns];

            // create a new cell
            Cell c = new Cell();

            for (int i = 0; i < r.ChildElements.Count(); i++)
            {
                // get current cell at i
                c = r.Elements<Cell>().ElementAt(i);

                string value = "";

                if (c != null)
                {
                    int cellReferencAsInterger = GetColumnNumber(GetColumnName(c.CellReference));

                    if (c.CellValue != null)
                    {
                        // if cell reference in range of the area
                        int start = startColumn;//GetColumnNumber(this._areaOfData.StartColumn);
                        int end = endColumn;//GetColumnNumber(this._areaOfData.EndColumn);

                        if (cellReferencAsInterger >= start && cellReferencAsInterger <= end)
                        {
                            // shared string
                            if (c.DataType != null && c.DataType.HasValue && c.DataType.Value == CellValues.SharedString)
                            {
                                int sharedStringIndex = int.Parse(c.CellValue.Text, CultureInfo.InvariantCulture);
                                SharedStringItem sharedStringItem = _sharedStrings[sharedStringIndex];
                                value = sharedStringItem.InnerText;
                            }
                            else { value = c.CellValue.Text; }

                            // define index based on cell refernce - offset
                            int index = cellReferencAsInterger - offset - 1;
                            rowAsStringArray[index] = value;
                        }
                    }//end if cell value
                    else
                    {
                        **if (cellReferencAsInterger >= startColumn && cellReferencAsInterger <= endColumn)
                        {**
                            int index = cellReferencAsInterger - offset - 1;
                            rowAsStringArray[index] = "";
                        **}**
                    }
                }//end if cell null
            }//for

            // replace all null values with "";
            for (int i = 0; i < rowAsStringArray.Length; i++)
            {
                if (rowAsStringArray[i] == null) rowAsStringArray[i] = "";
            }

            return rowAsStringArray.ToList();
        }`


highlighted is another test i added : 
since the method parses the whole row values and check if the index is between the selected areas, but only if the cell value is empty or null, it goes for saving it directly without checking if the index is within the range and also the list to be returned is initialized with the number of columns selected while selecting the areas.

**Comment by geofranzi** [comment]
@Hamdi1992  Did you also change the return value from the function?

**Comment by geofranzi** [comment]
..works now ...

**Comment by Hamdi1992** [comment]
should we close the issue then ?

**Comment by geofranzi** [comment]
I did not test your scenario. I have other "challenges", but was thinking maybe also covered with your changes ;-) ...we should not close it until it is committed in the code ;-)
