### ISSUE TITLE
Mapping assignment from party type to simple components, are ignored in the metadata

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#489]
Mapping assignment from party type to simple components, are ignored in the metadata and therefore no relationships can be defined.

**Comment by geofranzi** [comment]
![image](https://user-images.githubusercontent.com/15946467/77685157-4c5d0500-6f9b-11ea-9734-e777d2876f0d.png)

 ID not removed from value

**Comment by geofranzi** [comment]
works

**Comment by geofranzi** [comment]
It seems now the value is not anymore saved. 

Select a person (simple type) -> correct value shown (without ID)
save/validate/add new person  -> field is empty again

I tried to add a "afterClosed=false" inside the "if (simple === "True") {..."-Block ...value is saved, but without party id and with ID

**Comment by geofranzi** [comment]
if (partyidConverted !== null && partyidConverted > 0 && afterClosed === false) {
                        console.log(partyidConverted);
                        //UpdateWithParty(ParentStepID, ParentModelNumber, 0);

Do we still need this here? If we deactivate it, also complex works again. Otherwise form is empty, but correct values saved.

**Comment by DavidBlaa** [comment]
there is the case, if you enter something after you have entered a party, the party assignment must be deleted.
