### ISSUE TITLE
Improved access to metadata information (Title & Description)

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#498]
Currently information like title and description ... are always loaded directly from the metadata xml from the database.

We need improved access to this information. 

Maybe the information (extensible) is kept in a separate table or index

- [x] update dsv table with title, desciption
- [x] update code 
- [x] set title and description by every metadata change
- [x] after change metadata structure update all depending dsv
- [x] Update Script

**Comment by geofranzi** [comment]
Wenn wir die Spalten an die Dataset version anhängen könnten man die mit einem Trigger automatisch befüllen, dazu müsste man als VAR dann die dv.id einsetzen.
```SQL
Select (xpath('//' || (SELECT
  (xpath('//nodeRef/@value',xml_element))[1] AS "value"
FROM (
  SELECT unnest(xpath('//nodeReferences',m.extra)) AS xml_element FROM datasetversions dv left join datasets ds  on ds.id = dv.datasetref left join metadatastructures m  on ds.metadatastructureref= m.id  where dv.id = 10
) t where (xpath('//nodeRef/@name',xml_element))[1]::varchar = 'title') || '/text()', metadata))[1] as "test"  From  datasetversions dv  where dv.id = 10
```

**Comment by DavidBlaa** [comment]
https://github.com/BEXIS2/Core/commit/c71352652df8156ddb731fb8ea5e79cd01ae8071

**Comment by geofranzi** [comment]
Some numbers for "Create Dataset" (BE): 
before: 30-40s
after: 20s
Loop GetDatasetLatestVersion(id) -> GetDatasetLatestVersions(ids): 6s

**Comment by geofranzi** [comment]
""Failed for execute the submitted native query.  Reason: \u002742601: Syntaxfehler bei »)«\u0027"" (Save metadata structure)
