### ISSUE TITLE
DIM Mapping: Our current transformation rules can not handle double names 

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#517]
Any idea how we can handle this?

FirstName[0] LastName[1]

e.g. Ernst-Detlef Schulze (712) --> Ernst Schulze Detlef (712)

**Comment by DavidBlaa** [comment]
[a-zA-Z\-]*

**Comment by DavidBlaa** [comment]
![image](https://user-images.githubusercontent.com/19665289/78757542-f31ea980-797c-11ea-972a-1408d1ab1617.png)

**Comment by geofranzi** [comment]
thanks :-)
