### ISSUE TITLE
Generic Entity Permission Check(s)

### ISSUE THREAD

**Issue by sventhiel** [BEXIS2/Core#519]
**Is your feature request related to a problem? Please describe.**
In general, different parties (re)use existing code for several purposes. For example, publications are of type "dataset". So it is desired to use controllers and functions of the dataset workflow.

But there it is necessary to check permissions for a different entity (even though it is type of dataset).

**Describe the solution you'd like**
Instead of method annotations, there should be a generic permission check that should be executed at the beginning of the desired function.

**Describe alternatives you've considered**
An alternative would be to copy desired code snippets and implement security checks separately.

**Additional context**
By default, the function should be able to check for any kind of entity.

**Comment by sventhiel** [comment]
It seems not be recommended to put these checks inside the logic of managers and/or entity repositories. Currently, my idea is to create at least an IQueryable extension to check entity permissions.

The benefit is, that developers are free to put the check where they like. The drawback is that there are no automatic checks inside. So the developer has to trigger it.

**Comment by DavidBlaa** [comment]
fixed and tested with entites
