### ISSUE TITLE
Is it possible to mount a single Bexis instance from a multi-instance server, remotely on a pc via IIS without having access to the other sites?

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#528]
Is it possible to mount a single Bexis instance from a multi-instance server, remotely on a pc via IIS without having access to the other sites?

**Comment by sventhiel** [comment]
What do you mean by "having access"?

In general, it is possible to host multiple instances on the same machine with different domains. But as soon the server is publically available, all websites will be available from the internet.

But is this question still valid @DavidBlaa?
