### ISSUE TITLE
How is it possible to edit the workspace without connecting to the server?

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#529]
The settings and changes must be saved and accessible only to a specific group.

**Comment by geofranzi** [comment]
Done with the refactoring of our settings.

**Comment by sventhiel** [comment]
Yes, in general parts of the workspace (especially most of the settings) are accessible through the web ui. But there are still some parts (i.e. required files) that are only manageable with direct file access (i.e. remote access).
