### ISSUE TITLE
Validation "fails" for data upload with date & time

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#537]
- [ ] fix validation
- [ ] add unit tests
---
test the upload of different date & time pattern and check how it is finally represented in the DB:

- [x] 10:20
- [x] 1:30
- [x] 1:30 PM
- [x] 01:30
- [ ] 2006-2-2
- [ ] 2006-02-02
- [ ] 5/10/2014 12:00:00 AM
- [ ] ...

import and export should result in similar/same results: https://github.com/BEXIS2/Core/issues/534

**Comment by DavidBlaa** [comment]
testcase added in test quality

**Comment by geofranzi** [comment]
Display pattern: yyyy-MM-ddTHH:mm:ss
Test data: 5/10/2014;
Validation: true
Result data: "" (empty value)

**Comment by geofranzi** [comment]
format: text
pattern: yyyy-MM-dd
"iso date"
30
30.5

--> converted to a date. In theory, this should only happen with Excel etc. input.(?)

**Comment by DavidBlaa** [comment]
> format: text
> pattern: yyyy-MM-dd
> "iso date"
> 30
> 30.5
> 
> --> converted to a date. In theory, this should only happen with Excel etc. input.(?)

yes, in the case of excel a double value is set in the cel.

**Comment by DavidBlaa** [comment]
--> @geofranzi
Add date pattern to error message #537 - LIKE :D

**Comment by geofranzi** [comment]
> > format: text
> > pattern: yyyy-MM-dd
> > "iso date"
> > 30
> > 30.5
> > --> converted to a date. In theory, this should only happen with Excel etc. input.(?)
> 
> yes, in the case of excel a double value is set in the cell.

do we know during validation, if the source was excel or not? If yes we should use the info and only try to convert from double values if the source was Excel.

**Comment by DavidBlaa** [comment]
in the future there will be not date without display pattern.
i add the display pattern for this examples in the system und run test over it.
so its possible to get the right stuff with this examples and the right display pattern.
