### ISSUE TITLE
Order by timestamp & dataset version

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#539]
If an older version of primary data is shown, the order of the tuples can be shifted or even random because it is currently ordered by timestamp. This also leads to the effect, that changed tuples always on the bottom. 

This happens with original BEXIS 2 data (timestamp for initial insert not set) and BE migrated data (timestamp set, but also identical).

Possible solution:
- Add a new attribute to tuples ("original_Id")
- map the ID from the original tuples 
- map the Original tuple ID from the Historic tuples 
- Order by: original_Id instead of timestamp.

- [ ] check where also tuples order by timestamp has been used and should/could be replaced as well

**Comment by DavidBlaa** [comment]
ref #232

**Comment by DavidBlaa** [comment]
test is created

**Comment by DavidBlaa** [comment]
@geofranzi  haben wir hierfür ein update script gemacht oder müssen wir da noch drüber nach denken?

**Comment by geofranzi** [comment]
Nein wir brachen kein update script
