### ISSUE TITLE
Enter long text in a text input - Fail

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#554]
It is possible to enter a longer text. The warning is shown, but you can still save it with more than 255 chars.

<br>

<br>

**Comment by geofranzi** [comment]
https://bexis2.testquality.com defect [D84](https://bexis2.testquality.com/project/8555/result/2004014/defect/6734). Do not remove or edit.

**Comment by DavidBlaa** [comment]
ist not a bug, you can store datasets with metadata that is not valid
