### ISSUE TITLE
Sort Users/Group - Fail

### ISSUE THREAD

**Issue by EleonoraPetzold** [BEXIS2/Core#556]

**Comment by EleonoraPetzold** [comment]
https://bexis2.testquality.com defect [D86](https://bexis2.testquality.com/project/8555/result/2004219/defect/6736). Do not remove or edit.

**Comment by geofranzi** [comment]
I assume it is sorted by the account name and not by the user name. I guess we replace it after the sorting ....

**Comment by DavidBlaa** [comment]
ref #555
