### ISSUE TITLE
Sync a dataset - Fail

### ISSUE THREAD

**Issue by EleonoraPetzold** [BEXIS2/Core#557]
I'm not able to open "Manage Datasets" with the first click on it. In out BE instance we have the same problem. After reload it works.
![image](https://user-images.githubusercontent.com/42029171/82429474-43188200-9a8c-11ea-85ec-df3cf0d648a0.png)

**Sync successful!**

**Comment by EleonoraPetzold** [comment]
https://bexis2.testquality.com defect [D87](https://bexis2.testquality.com/project/8555/result/2004222/defect/6737). Do not remove or edit.

**Comment by DavidBlaa** [comment]
over a longer period of time the problem was tested again and again but did not occur again. the ticket is now closed, if it occurs again we have to open it again
