### ISSUE TITLE
Edit a unit - Fail

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#558]
**Step 1 Pass**

Navigate to Edit Unit via Unit Manager.

**Step 2 Pass**

Edit Unit

**Step 3 Fail**

Click "Save"

With/without changing something: Error because of duplicate abbreviation

<br>

<br>

**Comment by geofranzi** [comment]
https://bexis2.testquality.com defect [D88](https://bexis2.testquality.com/project/8555/result/2004055/defect/6742). Do not remove or edit.

**Comment by DavidBlaa** [comment]
in general the system works correctly by not allowing duplication in the abbreviations. the problem here is the seed data. there are already duplicate and spelling mistakes in there.
this has now been changed in the current workspace and will no longer exist, at least not in the new instances.
