### ISSUE TITLE
Lock Data Type by Unit - Fail

### ISSUE THREAD

**Issue by EleonoraPetzold** [BEXIS2/Core#565]
**Step 1 Pass**

Navigate to Create or Edit a Unit via Unit Manager

**Step 2 Pass**

Fill mandatory fields.

**Step 3 Pass**

Tick a non-locked Data Type.

**Step 4 Fail**

<span lang="EN-US">Click&nbsp;</span>

“Save”

**datatype is't locked.**

**Comment by EleonoraPetzold** [comment]
https://bexis2.testquality.com defect [D91](https://bexis2.testquality.com/project/8555/result/2004062/defect/6764). Do not remove or edit.

**Comment by DavidBlaa** [comment]
its not a bug
