### ISSUE TITLE
View party refers to an error

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#573]
Test system: BEXIS 2 RC 2.14.0.1
Test browser: Google Chrome

**Describe the bug**
I created three same party relationships from party person to a party organization. Then I wanted to view the party person that the error message interrupted me.

![party_view](https://user-images.githubusercontent.com/20185586/83241632-67b2df00-a19b-11ea-949f-7e8975db3a76.png)

**Comment by DavidBlaa** [comment]
over a longer period of time the problem was tested again and again but did not occur again. the ticket is now closed, if it occurs again we have to open it again
