### ISSUE TITLE
Error after delete a party relationship

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#574]
Test system: BEXIS 2 RC 2.14.0.1
Test browser: Google Chrome

**Describe the bug**
I have a person with three relationships. I deleted one relationship and clicked on the Back button. The error appeared.

![party_delete](https://user-images.githubusercontent.com/20185586/83244212-4d7b0000-a19f-11ea-8931-191c6fd4b065.png)

**Comment by navabpourn** [comment]
I can view the page after the refresh.

**Comment by DavidBlaa** [comment]
over a longer period of time the problem was tested again and again but did not occur again. the ticket is now closed, if it occurs again we have to open it again

#573
