### ISSUE TITLE
Upload csv files that contains variable names with double quotes - Fail

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#591]
**Step 1 Pass**

Navigate to upload Data

**Step 2 Pass**

Select Tabular

**Step 3 Pass**

Select the csv file and click next

**Step 4 Pass**

Set the file informations and click next

**Step 5 Pass**

Select the dataset and click next

**Step 6 Fail**

Select the validate Button

**Step 7 Fail**

finish the upload

- A variable of the data file does not exist in the data structure. Check your variable names in your file and data structure. Names need to be identical. ("v1","v2","v3")
- Data structure does not have the same order. Check your variable names and order in your file and data structure. Names need to be identical. ("v1","v2","v3")

**Comment by DavidBlaa** [comment]
https://bexis2.testquality.com defect [D103](https://bexis2.testquality.com/project/8555/result/2004049/defect/6820). Do not remove or edit.

**Comment by geofranzi** [comment]
Did you select "double quote" during upload? This works for me ...

**Comment by DavidBlaa** [comment]
You're right, I forgot to pick the double quotes.

**Comment by DavidBlaa** [comment]
I forgot to pick the double quotes.
