### ISSUE TITLE
Error: importing "a large dataset"

### ISSUE THREAD

**Issue by prteixeira** [BEXIS2/Core#601]
Error when importing "a large dataset" (xlsm format), for example, with 17532 rows and 41 columns. The result, at the primary dataset and downloaded dataset, shows the dataset with only 10001 rows and 41 columns.

**Desktop:**
 - OS: Windows 10
 - Browser Google Chrome
 - Version  83.0.4103.116 (64 bits)

![image](https://user-images.githubusercontent.com/4464858/87036144-5b696b00-c1b8-11ea-828e-7c8968c4badb.png)

![image](https://user-images.githubusercontent.com/4464858/87036317-a4b9ba80-c1b8-11ea-9f77-c32c9a34bcd2.png)

**Comment by geofranzi** [comment]
@DavidBlaa it fixed, right?
