### ISSUE TITLE
Admin/Curation/User: Show, if a linked metadata field is linked or filled with free text

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#607]
As we can and/or do not want to force linked metadata fields (e.g. with Person or projects) are filled based on a selection from a (autocomplete) list we need an easy way for admins/data curators to see if filled fields are linked with an ID or not (free text).

This is important if those fields are used to inform all data owners and bound permission rights or to avoid many different ways of writing e.g. for project names.

**Comment by geofranzi** [comment]
- simpleAttribute: grün / red for linked not lined
- complex: not possible to show, but associated fields are locked
- help text on top

![image](https://user-images.githubusercontent.com/15946467/114058831-1a5fcd80-9894-11eb-9925-2b96010797bc.png)

**Comment by DavidBlaa** [comment]
here were found some UI Issues
