### ISSUE TITLE
Create a data structure with variables whose names are the same

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#612]
I have a data table with two column variables called "comment". The creation of this data structure in BEXIS 2.14 is not possible due to the prohibition of double variable names. 
In this example, I can change the comment to remark, but there are cases where the variable names are really important and cannot change.

**Comment by geofranzi** [comment]
If two columns have the same name and same content the question is more, why it is divided into two columns. If those two columns have different content (or a different source) they should have a different name. Like in your case it is something like "comment1" and "comment2".

**Comment by sventhiel** [comment]
Hej @navabpourn,

thanks already a lot to @geofranzi. I agree with you. But maybe @navabpourn could give us a more precise example or more information about the fact, why it should be necessary to use multiple variables with the same name.

Cheers, Sven

**Comment by navabpourn** [comment]
Hi,
I talked with data producers and found that they do not have the same variables in a data table. In that example that I had, comments are related to different topics. So the variable names should be different. 
Thanks anyway. We can close this conversation.
