### ISSUE TITLE
if a dataset is deleted, a request may link to a deleted dataset. How do we handle this?

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#615]
...

**Comment by geofranzi** [comment]
add error handling @place of potential error:
- [ ] normal user do not see pending / open / done requests referring to deleted datasets
- [ ] admin will see the orphans, replace title by:  "Dataset currently / no longer accessible".

**Comment by DavidBlaa** [comment]
- [ ] check links
