### ISSUE TITLE
Registration form: prevent to fill out by bots

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#622]
as we can see in the demo version, we collect a lot of nonsense registrations.

**Comment by sventhiel** [comment]
Do you prefer a specific kind of "anti-bot"/"I am not a robot" check/verification? There are different open/free solutions. What is about other projects, that don't want to use one of those - e.g. Google ReCaptcha.

**Comment by geofranzi** [comment]
Works for iDiv and BE now
