### ISSUE TITLE
Force js files are renewed in the browser cache after change

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#623]
e.g. add the file date (see https://stackoverflow.com/questions/15041603/how-to-prevent-the-browser-from-caching-a-json-file/15041641#15041641)

**Comment by DavidBlaa** [comment]
there are several ways to fix this.

### web.config
````xml
<!-- reset the cache after one day -->
<clientCache cacheControlMode="UseMaxAge" cacheControlMaxAge="1.00:00:00"/>
````

### code

whenever a json file is added, a version or date must be appended.
here i see the problem, that surely not all developers always have this in mind

````c#
<script src="@Url.Content("~/Areas/Dcm/Scripts/Form.js?v=+'@app.version'+")" type="text/javascript"></script>;
````

### IIS
there is also a way to set this in iis.
![image](https://user-images.githubusercontent.com/19665289/89003692-be09de80-d300-11ea-96aa-707c714808d4.png)

generally, the problem only occurs if the iis is not restarted. I like the idea of setting it centrally, even if it is not executed directly.

**Comment by DavidBlaa** [comment]
is allready set in the web config. do we need more?
