### ISSUE TITLE
Missing dispose for manager

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#628]
There are several datasetManger (and maybe also other manager) calls without a using/dispose.

- [x] add using (easier to read as try ...)
- [ ] check function (new problems can occur related to lazy loading)

**Comment by geofranzi** [comment]
List to check (...new Manager & disposed() ):
[test.txt](https://github.com/BEXIS2/Core/files/5018157/test.txt)

**Comment by geofranzi** [comment]
```
import glob, os

os.chdir("C:\Daten\Documents\BEXIS_Project\Core_bexis")
for file in glob.glob("**/*.cs", recursive=True):
    print(file)
    # Using readline()
    file1 = open(file, 'r')
    count = 0

    for line in file1:
        count += 1

        if line.__contains__("Manager = new "):
            print(count.__str__() +": "+ line)
            # manager = [w for w in line.split() if w.endswith('Manager')]
            # print(manager)
        if line.__contains__(".Dispose()"):
            print(count.__str__() +": "+ line)


    file1.close()
```

**Comment by geofranzi** [comment]
![image](https://user-images.githubusercontent.com/15946467/89350128-b440fc00-d6af-11ea-88f5-c520bc630316.png)
we can show / search for it :-)

**Comment by geofranzi** [comment]
- [ ] lazy loading problem in manage parties
- [ ] (ids shown instead of name ..correct?)
![image](https://user-images.githubusercontent.com/15946467/89687818-28261300-d901-11ea-9d59-c05e4d6ea752.png)
![image](https://user-images.githubusercontent.com/15946467/89687878-4855d200-d901-11ea-9436-c46d27ded549.png)

**Comment by geofranzi** [comment]
GlobalAnalysisRules
- .editorconfig
- GlobalSuppresions.cs
`[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Codequalität", "IDE0067:Objekte verwerfen, bevor Bereich verloren geht", Justification = "<Ausstehend>", Scope = "type", Target = "System.Data.DataTable")]`

**Comment by geofranzi** [comment]
Download not working
![image](https://user-images.githubusercontent.com/15946467/91154308-ab958180-e6c1-11ea-8c7e-a876d0d4879a.png)

**Comment by DavidBlaa** [comment]
release is out, so i close this issues
