### ISSUE TITLE
Improvement on the constraints for the data check: Domain terms space should be enlarged

### ISSUE THREAD

**Issue by Yuanyuan-Huang** [BEXIS2/Core#632]
- [ ] increase size in db

I tried the “constraints” on the variable template by setting the “Domain”. However, I realized that there is limited character number (255 Characters including space) in the “Domain” part. For example, in the domain part, the terms can only be from “p1, p2, p3, …p52, p53” , but not any more. Even if I have “P54”, “p55” etc, the item can’t contain them anymore.
The code is: if (str.Length > 255) str = str.Substring(0, 255);

**Describe the solution you'd like**
Could you enlarge space of “Domain” part by deleting this "255 constraint" code?

**Describe alternatives you've considered**
It will be even better if a index table (e.g. csv file) could be implemented to check the variable values. For example if the uploaded data has species names, then the variable "species" will be checked through this list. If there is no match, then show warnings to ask people to correct it.

Looking forward to seeing this feature in the next version.

**Comment by aostrow** [comment]
Other options would be to
- link to a domain values table of the db
- link to an variable of a dataset

**Comment by geofranzi** [comment]
has been solved.
