### ISSUE TITLE
Data quality control during uploading data through "Import"

### ISSUE THREAD

**Issue by Yuanyuan-Huang** [BEXIS2/Core#633]
**Is your feature request related to a problem?**
The constraints that I defined for the variable template are currently not checked at "Import" function.  So if I upload the data through "Import", it's impossible to have any variable quality control.

**Describe the solution you'd like**
Including the Constraints check in the "Import" function, such as checking the pattern or the Domain terms.

**Comment by geofranzi** [comment]
The easy upload will be deprecated in 2.15 and replaced by #824
