### ISSUE TITLE
Error: Primary data and downloaded data file

### ISSUE THREAD

**Issue by prteixeira** [BEXIS2/Core#637]
**Describe the bug**

- Download of the portal file: the data files are out of order / not classified (figures A and B, dark red);

- My first column is defined as TimeStamps with datatype/format equal the dd.mm.yyyy and the second column is defined as Yr (datatype/format: year, format yyyy). In the ATTO Data Portal, in the  TimeStamps and Yr columns, the values presented are mistaken. Another problem is in the downloaded data file, in all output formats, the TimeStamps and Yr change to incorrect value (figure A, red box) and out of order.

**Screenshots**

![image](https://user-images.githubusercontent.com/4464858/91865836-cc208700-ec3f-11ea-8f95-dc582b6b003c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (64-bits)
 - Browser Firefox 74.0 (64-bits)
 - Bexis version 2.14

**Comment by DavidBlaa** [comment]
in consultation with marcus we have checked the problem again and it has already been fixed by the past patches. therefore i will close the issue now. thanks for the input
