### ISSUE TITLE
Add "Variable Description" and "Missing Values" setting in Import Data function

### ISSUE THREAD

**Issue by Yuanyuan-Huang** [BEXIS2/Core#644]
**Is your feature request related to a problem? Please describe.**
When I have NAs in the numeric variable in the data and use Import Data function, there is no way to validate it. For the data structure with the datasets that uploaded with "Import Data" function, there is no description of the variables. It's not clear for the data then.

I prefer to use Import Data instead of "Upload Data". "Upload Data" can only be used when you created the data structure first and the data structure need to be exactly the same sequence and same column name. It takes a lot of time.
With Import Data function, the sequence and the column name is more flexible. But it needs to have variable description and allow NAs (character) in the numeric variables.

**Describe the solution you'd like**
Add "Variable Description" and "Missing Values" setting in Import Data function

**Comment by Yuanyuan-Huang** [comment]
I just realized that you can edit the data structure in the dataset that you created with "Import Dataset". There you can edit the data variable descriptions. We may only need to add "data structure edit/data variable description edit" button  to make it clear that you can edit the data structure.

**Comment by geofranzi** [comment]
The easy upload will be deprecated in 2.15 and replaced by #824
