### ISSUE TITLE
Add a functionality to the upload to only append rows

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#66]
**Is your feature request related to a problem? Please describe.**
The upload is too slow. it takes long because we need to check, wich row is a new one and wich one should be updated.

**Describe the solution you'd like**
e.g. If i have sensor data, i dont need to update row because the data is generated sequentially.

**Comment by navabpourn** [comment]
Hey @DavidBlaa! On which branch could I test it? The branch of issue #66 does not exist or I don't see it.

**Comment by DavidBlaa** [comment]
Hey @navabpourn. The branch is online. 
you need to fetch in visual studio.

![image](https://user-images.githubusercontent.com/19665289/41393552-a812313c-6fa6-11e8-81c1-ad9f5696b284.png)

**Comment by navabpourn** [comment]
Well, I can not go over update data by defining the primary key. After clicking the Next button, the defined primary key is gone and a warning message tells me: Define a primary key combination and check it please.
@DavidBlaa

**Comment by navabpourn** [comment]
@DavidBlaa The upload process is blocked after specifying the dataset.

**Comment by DavidBlaa** [comment]
sorry, you need to update the submittaskinfo.xml in the workspace/modules/dcm.

<stepInfos>
	<stepInfo title="Select File" action="SelectAFile" area="DCM" controller="SubmitSelectAFile"/>
	<stepInfo title="Get File Information" action="GetFileInformation" area="DCM" controller="SubmitGetFileInformation"/>
	<stepInfo title="Specify Dataset" action="SpecifyDataset" area="DCM" controller="SubmitSpecifyDataset"/>
	<stepInfo title="Choose Update Method" action="ChooseUpdateMethod" area="DCM" controller="SubmitChooseUpdateMethod"/>
	<stepInfo title="Validation" action="Validation" area="DCM" controller="SubmitValidation"/>
	<stepInfo title="Summary" action="Summary" area="DCM" controller="SubmitSummary"/>
</stepInfos>

**Comment by DavidBlaa** [comment]
please download the latest workspace for the version 2.12 from the demo server

**Comment by navabpourn** [comment]
It works fine :)
