### ISSUE TITLE
Public search (metadata) : hide email for bots

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#692]
If metadata contains email addresses and those are public, also the email addresses are exposed as plain text. 

We should think about how we want to prevent this. Either hiding those fields in the public mode or display it "correct".

issue found in iDiv

**Comment by aostrow** [comment]
https://www.heartinternet.uk/blog/15-ways-to-hide-your-email-address/

**Comment by aostrow** [comment]
https://github.com/martignoni/hugo-cloak-email

**Comment by geofranzi** [comment]
https://github.com/geofranzi/iDiv-Data-Portal/commit/5adc3df7ae08cfffec0d1b00d5b7af48aa4e493e#diff-29a40861bafe31e774190c795fc6fe4b8c012fea4707010f4102e52d74eafa15 

individually done in iDiv and BE

**Comment by geofranzi** [comment]
move to the core as there are also other instances with the same name "Email"
