### ISSUE TITLE
File Upload: Require/Allow a description

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#704]
**Is your feature request related to a problem? Please describe.**
A description is a component to check the dataset's relevancy. Therefore a meaningful description raises the dataset quality.

**Describe the solution you'd like**
I would suggest storing a short description at the upload time and show it on the dataset detail view, next to the file name.

**Comment by geofranzi** [comment]
Attachments have a description. Unstructured primary data should be described within the main metadata. I see no reason to add additional info here.

**Comment by navabpourn** [comment]
Why not? Who can force people to describe files in the metadata? I think each component should have its own specifications independently.

**Comment by geofranzi** [comment]
Also requested in BE ...moved to 2.15

**Comment by geofranzi** [comment]
#818

**Comment by geofranzi** [comment]
will work in Version 3.0.0 see #818
