### ISSUE TITLE
Variable templates must open to review

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#705]
Even if a variable template is not editable, the user needs to study the variable template specifications. 
The variable template review page should open with a special URL to be available independently.

**Comment by geofranzi** [comment]
The template itself is only relevant during creation. All var info is shown here: 
![image](https://user-images.githubusercontent.com/15946467/108085303-7a48ad80-7075-11eb-9112-8588766227d6.png)

Note: Using Easy upload is not recommended as it has no information on the variable templates, no option to declare missing values, and only works for excel files.

**Comment by navabpourn** [comment]
Look at this. Variable templates used in this data structure have descriptions, but they are deleted in variables. It could be helpful if I can click on each variable and see more details.

![Capture2](https://user-images.githubusercontent.com/20185586/108092982-86d10400-707d-11eb-8737-70bada2c8291.JPG)

**Comment by geofranzi** [comment]
The default description are now per default deleted during data structure creation as they describes the data type and not the content. 
![image](https://user-images.githubusercontent.com/15946467/108100789-a882b900-7086-11eb-902d-6e4316725ba3.png)

To show that text later as well brings no additional information for a user. Instead, during upload, the description field should be filled describing the data itself.

**Comment by geofranzi** [comment]
and yes also other examples, but you do not know before how they are described ...

![image](https://user-images.githubusercontent.com/15946467/108101464-8b9ab580-7087-11eb-8fab-b1efc9221594.png)

**Comment by navabpourn** [comment]
Then what is the benefit of using a template? People use predefined templates because they don't want to spend time creating a new thing. Writing descriptions for forty-five variables while creating a data structure is time-consuming (2x 45: first creating variable templates and then using them to create a data structure!!!!).

**Comment by navabpourn** [comment]
All your screenshots are from the data structure manager. Not all users have access to this part. Many users can only see the data structure tab in the dataset detail view. A data consumer expects to get enough information from the dataset details (not look for details throughout the site). In the data structure tab, you can see the name and other specifications of variable templates except description. It can help if data consumers can click on the variable template and see details. 
![Capture3](https://user-images.githubusercontent.com/20185586/108122199-328d4a80-70a4-11eb-86d2-f679f7c9a7c8.JPG)

**Comment by geofranzi** [comment]
From v3.0 variable templates lose the current function and stay only for provenance at the variable. All Information are copied to the variable and everything can be viewed.
