### ISSUE TITLE
Import Data allows creation of datastructure with non-unique variable names

### ISSUE THREAD

**Issue by MaSteinberg** [BEXIS2/Core#71]
When uploading a file with the Import Data workflow and selecting multiple cells with the same content as header area (and ignoring suggestions during verification step), a datastructure will be created that contains different variables with the same name.
This should not be possible since creating a datastructure manually enforces uniqueness for the variable names.

**Comment by DavidBlaa** [comment]
available in r2.12 rc3

**Comment by DavidBlaa** [comment]
tested in rc3 and works fine
