### ISSUE TITLE
ActionInfo -> IsComplete() checks 3 times the same issue

### ISSUE THREAD

**Issue by EleonoraPetzold** [BEXIS2/Core#721]
See here:
https://github.com/BEXIS2/Core/blob/1e794a733b848848a7cb82cbbc478034cb647daf/Modules/DCM/BExIS.Dcm.Wizard/ActionInfo.cs#L61

check area and controller are missing.

**Comment by sventhiel** [comment]
Hej,

in general, that is true. So if the route is going to be checked, the system needs to verify action, controller and area. But at least there will be an issue with **_AreaName_**, because I think the routing is working for empty **_AreaName_** similar to **_AreaName = Shell_**.
