### ISSUE TITLE
View party:  conditional attribute not shown

### ISSUE THREAD

**Issue by aostrow** [BEXIS2/Core#725]
in profile we have
![image](https://user-images.githubusercontent.com/26480843/109637559-3bbef280-7b4d-11eb-8c47-9adfca4f2317.png)

in manage party we have
![image](https://user-images.githubusercontent.com/26480843/109636258-a707c500-7b4b-11eb-89a7-78c743b229f4.png)

**Comment by geofranzi** [comment]
works fine in Edit mode. Does not in (admin) view mode.
