### ISSUE TITLE
System variable not always set correct

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#727]

**Comment by geofranzi** [comment]
![image](https://user-images.githubusercontent.com/15946467/111035063-dacece80-8418-11eb-8593-505d54031a30.png)
 should be datasetId?

**Comment by geofranzi** [comment]
Version also wrong set sometimes

**Comment by aostrow** [comment]
observed behavior in https://www.bexis.uni-jena.de/ddm/data/Showdata/30915
- metadata edit (v7): 
  - **shorten (metadata) Id** entry to 3
  - **added +2 to version** entry (=8)
- file deleted (v8): ok (keep shortened Id, v+1)
- file uploaded (v9): ok (keep shortened Id, v+1)

**Comment by geofranzi** [comment]
Upload & Delete of file overwrite previous metadata version with (new) current

**Comment by geofranzi** [comment]
It happens here:
![image](https://user-images.githubusercontent.com/15946467/118333433-fe42f200-b50b-11eb-8706-565f9c4edad7.png)

**Comment by geofranzi** [comment]
Solution?  seems to work ...
![image](https://user-images.githubusercontent.com/15946467/118338185-c476e900-b515-11eb-9bd1-ff16d2821756.png)
