### ISSUE TITLE
wrong subject email from system

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#743]
**Describe the bug**
Whenever a dataset is updated, even when the metadata is edited, I receive an email with the subject "BEXIS - Data uploaded". In the body of that email is specified that the dataset is updated. The subject should be changed to "updated" too.

![dataset updated](https://user-images.githubusercontent.com/20185586/112472887-f1a4e780-8d6d-11eb-8bac-ca67fdac3024.PNG)

**Comment by sventhiel** [comment]
Hej,

I am going to check that within the next days. But as far I took a look into the whole procedure - there seems to be a difference between metadata and primary data "updates". But also some strange occurrences as well - e.g. email header of dataset update within certain cases of a dataset download.

May it is necessary to "refactor" the messages and provide proper information for both, users and admins.


Best regards
Sven

**Comment by geofranzi** [comment]
https://github.com/BEXIS2/Core/commit/501d4a76800c73d04184644eaa194c72df836004 already fixed. Will be part of the next patch.
