### ISSUE TITLE
Column filtering for NA does not work on the primary data

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#744]
**Describe the bug**
The column filtering does not work on the primary data except for the first column.

**Desktop:**
 - Browser: Chrome
 - BEXIS2 version: 2.14.3

**Additional context**
![filter](https://user-images.githubusercontent.com/20185586/112596536-4008c380-8e0c-11eb-8c3e-52f7f7d465a9.png)

**Comment by geofranzi** [comment]
![image](https://user-images.githubusercontent.com/15946467/112905917-96ffe880-90eb-11eb-83b7-f57b4774eb35.png)
works in BE. Your description is very unspecific. What did you type in? What happened?

**Comment by navabpourn** [comment]
I have found that I cannot search for a text between numeric values. When the data type is double, and I want to search for "na" nothing happens when I tap a character like "n". It is working with numeric values.

**Comment by geofranzi** [comment]
Ok, that’s clear now. To search for na is not possible with the current telerik table. I will close the issue as it can not be fixed now and and belongs to the replacement of the table which is already on the to do list and will solve several issues.

**Comment by geofranzi** [comment]
moved to #747
