### ISSUE TITLE
Data structure edit: Order number can have gaps, but should not

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#745]
If the order number have gaps, it points to the wrong position in the array and the mv can not be build
![image](https://user-images.githubusercontent.com/15946467/113110253-277f1b80-9207-11eb-9dc3-ea73f5cafe19.png)

**Comment by geofranzi** [comment]
Solved by saving again the data structure (+ delete mv & sync). Unknown how to reproduce.

**Comment by MaJoHo** [comment]
This is the normal behavior on save the order is newly created so gaps will not exist. That was a problem long time ago and was fixed.

**Comment by geofranzi** [comment]
It happened last week in BE.

**Comment by geofranzi** [comment]
How to reproduce:

1. - Save as
2. - Delete Variable
3. - **Save (wrong order)**
4. - Save (order correct)
