### ISSUE TITLE
DDM UI Issues

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#76]
- [x] Merge download Buttons of Excel format
- [x] Add filetype to download buttons 
- [x] Remove id and latest version flag
- [x] Refactor Request and Desicions Tables in Dashboard (remove usless ids and add title) 
- [x] Reorder Leftpane of dashboard page - lv1 entity, lv2 my entites, requests,desicions
- [x] Reduce the space of the ID column in the search result grid
- [x] Merge Search and public search to one page with toogle
- [x] Primary data with many variables are not readable in the primary data view.

**Comment by navabpourn** [comment]
It seems all options are available in RC6 :)
