### ISSUE TITLE
Installation of BEXIS2

### ISSUE THREAD

**Issue by shahab-ab** [BEXIS2/Core#763]
![grafik](https://user-images.githubusercontent.com/7823110/117262751-e1deef80-ae51-11eb-9c3f-ead19667b7a4.png)

and by clicking on the search manager :
![grafik](https://user-images.githubusercontent.com/7823110/117262723-dbe90e80-ae51-11eb-8286-760a0deadf85.png)

**Comment by DavidBlaa** [comment]
Hello,

thank you for the issue report.

**Can you leave some more info?**
Which instance is it?
What page/button did you go to or click before the error occurred?
Were you logged in as a user?

**If you have access to the server:**
1. Is the SearchIndex available in the workspace?

**Comment by shahab-ab** [comment]
Hello,
Thank you for your quick feedback.
1. Version 2.14.2 (new deploy) / WINServer19
2. Homepage (under localhost)
3. No, I just browsed the site.

Ye I have access: 
SearchIndex Folder located under: C:\inetpubs\wwwroot\bexis\Workspace\Modules\DDM\Lucene\

**Comment by DavidBlaa** [comment]
**Ok here's what I suspect:**

>We don't publish a SearchIndex in the workspace, so the folder "../Workspace/Modules/DDM/Lucene/SearchIndex" exists but the files under e.g. BexisSearchIndex should not exist.

>The search is publicly accessible at the first initialization. But because the files are missing, an error is thrown. (its a bug and should be solved in the future)
The error page now, unfortunately, shows a link to a page that should only be accessible to registered users with specific feature permissions and is therefore not publicly accessible.

>You were not logged in and therefore an error is thrown.


Please execute the following.

**1. please open the Feature Permissions Page**

![image](https://user-images.githubusercontent.com/19665289/117273089-15bf1280-ae5c-11eb-8481-1c91bd8095ae.png)

**2. set Manage Search on Public**

![image](https://user-images.githubusercontent.com/19665289/117273229-39825880-ae5c-11eb-808d-7ed74bd8f5c6.png)

**3. Refresh Page, clear all sessions, because the menu links are stored in a session and open Manage Search**
![image](https://user-images.githubusercontent.com/19665289/117273802-be6d7200-ae5c-11eb-9751-3556b62afe6e.png)

**4. refresh search index**

![image](https://user-images.githubusercontent.com/19665289/117274037-f83e7880-ae5c-11eb-8d67-28af956b89af.png)


**After that an empty search should be loaded.**

This is not the general procedure but the fastest one.
Please save "Search Management" again by removing the public tick.

**Another way would be to register and then give yourself the rights to the page.**

The first user has access to the features permissions and should then secure the page (remove the tick) after the user has given himself the rights for the page! After that, no one can access the feature from the outside.

**Comment by shahab-ab** [comment]
Thank you,
I followed the instructions - The solution did not help after I click on the green button the same page (my 1st screeshot) appears. Additionally Login leads to the error page (2nd screenshot) .
The register page loads but after filling fileds and clicking on register button another error occures: as following:
![grafik](https://user-images.githubusercontent.com/7823110/117278255-e5c63e00-ae60-11eb-81ec-869a434405b9.png)

**Comment by geofranzi** [comment]
The email settings are not correct or not set.
the credential file is located in the workspace under General / Configurations

**Comment by shahab-ab** [comment]
I have given an e-mail address in web.conf - and smtp email in credentials config in workspace/general are correct. It should also be mentioned that I have disabled LDAP in credentials. Must it be always enabled?

**Comment by geofranzi** [comment]
For which purpose you are setting up a BEXIS instance? If your organization does not provide LDAP authentication just set it to false.

Please keep in mind we can are currently not able to provide support outside of any kind of cooperation with our department. If you have any relation to us, please let us know.

**Comment by shahab-ab** [comment]
For research data management purposes we aim to test Bexis on our university DUisburg-Essen. We have LDAP - but in test phase, I just want to report the problems that I run into after deployment. As you see it does not work with an ldap option being set to false and neither of previous problems have been solved.

**Comment by geofranzi** [comment]
We have a demo instance https://demo.bexis2.uni-jena.de/ .if you just like to play with it. Unfortunately, it's a little bit slow at the moment due to recent network changes at the university level.

**Comment by shahab-ab** [comment]
Thank you, actually it is not only working with - this is the deployment phase in which some basic problems exist.

**Comment by geofranzi** [comment]
In the already published version 2.14.3 some issues with university smpt problems have been solved. (see https://github.com/BEXIS2/Core/issues/650). Also some changes happened in the configuration file. Does your Wokspave fit to the version you use? Seems "Ldap_Enable" is not defined (either with false or with true). 
with the current version under development (2.14.4 - will be released this month) also error handling related to the email configuration is already improved.

**Comment by shahab-ab** [comment]
Thank you for your time and effort - Yes ldap-enabled already exist in the credentials.conf with avalue set to false. The question which still remains is that if it is required to be enabled in order for the homepage to load? the demo version of yours works without register/login. 
I just copied the contents of the site folder into the IIS website directory as well as workspace folder itself. 
here's how the folder structure looks:
![grafik](https://user-images.githubusercontent.com/7823110/117449029-c520e580-af3f-11eb-940a-28479560c750.png)

**Comment by geofranzi** [comment]
Common folder structure:
- site
- workspace
If you locate your workspace somewhere else, you have to adjust the location in the web.config file. Here you also define a "Data" Folder (outside inetpub) as well as the system admin email and the location of the credential config. The IIS needs permission for the "Data" folder.

**Comment by shahab-ab** [comment]
Hello @geofranzi ,
Thank you for your helpful info.
**For The version: 2.14.12:**
Installation succeeded.
User registration and logiin work.
Feature Permissions and other management sections work.
**Problem**: "Forgot Password" email is not sent to the registered and activated user.
**Error**: The search Index may not exist -> manage search 
![grafik](https://user-images.githubusercontent.com/7823110/117877885-6b088300-b2a5-11eb-8508-27c9a1ab8ede.png)

While logged-in (public user has no access to manage search) : click on the green button in manage search leads to the following error: 
_Server Error in '/' Application.
Object reference not set to an instance of an object. 
Description: Object reference not set to an instance of an object. 
Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.
Source Error: 
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below. 	
Stack Trace: 
[NullReferenceException: Object reference not set to an instance of an object.]
   BExIS.Modules.Ddm.UI.Controllers.AdminController.RefreshSearch() in C:\Program Files (x86)\Jenkins\workspace\BEXIS2_Release\Console\BExIS.Web.Shell\Areas\DDM\Controllers\AdminController.cs:331
   lambda_method(Closure , ControllerBase , Object[] ) +62
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +157
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +22
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +228
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9873933
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +48
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +159_
_____________________________________________________________________
For next trials no error occured - an email at system email received: "The creation of the search index is finished." as well as on web interface.

but again on the home page: Error The search index may not exist... (same as above screenshot)
we have no data in our database - Is that error normal then?
-----------------------------------------------------------------------------------
**For the version 2.14.3:**
Database update script succeeded - create database was set always to false except on the first run of 2.14.2.
Website, and contents of the Workspace folder, configuration, and credentials updated and set. ( at the same folder structure as previous version). After update and running as the screenshot shows that Workspace should be placed whitin the websitefolder!

![BEXIS2143-WorkspaceError](https://user-images.githubusercontent.com/7823110/117879897-c471b180-b2a7-11eb-9e4a-318ef8a9d525.jpg)

I just removed the workspace folder into the requested directory (inside the website folder) and setting up web.config for workspace folder directory and credentials There was no error regarding the folder issue but one another error:

![BEXIS2143-ApplicationError](https://user-images.githubusercontent.com/7823110/117880397-5e395e80-b2a8-11eb-9f4c-a2c70b7528c8.jpg)

I am planinig to restore the previous version 2142 at the moment. Hope this feedback help if there is any bugs in software or in instructions.

With best regards,

**Comment by geofranzi** [comment]
works now. 

Reason for Error: Workspace -> SearchIndex files corrupted. Replaced by new files.
