### ISSUE TITLE
Data structure list: Show linked datasets for each data structure

### ISSUE THREAD

**Issue by CFuerstenau** [BEXIS2/Core#765]
**Is your feature request related to a problem? Please describe.**
we have a lot of unused data structures. UI based delete of data structure is difficult because I don't know if a data structure is linked to a dataset

**Describe the solution you'd like**
would like to have information under manage data structure which indicates if a data structure is used by a dataset and which dataset

**Comment by geofranzi** [comment]
![image](https://user-images.githubusercontent.com/15946467/118284937-47298500-b4d1-11eb-9ff9-1ac7e17042b3.png)
