### ISSUE TITLE
"Log in" title -> "NAME - Log In"

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#768]
- [ ] change to "Log In"
- [ ] move to controller and add instance (from tenant) name in front -> "BExIS - Log In"
![image](https://user-images.githubusercontent.com/15946467/118938136-9bf45200-b94e-11eb-9f6c-77a260297066.png)

**Comment by geofranzi** [comment]
@sventhiel  not possible because Session not accessible ..right?

![image](https://user-images.githubusercontent.com/15946467/121001532-ace4f600-c78b-11eb-945a-08be137e30e0.png)

**Comment by DavidBlaa** [comment]
there is a missing libary from vaiona that extends the session

**Comment by geofranzi** [comment]
Adding the lib, did not work ...

**Comment by DavidBlaa** [comment]
after adding ..
using Vaiona.Web.Extensions;
using Vaiona.Web.Mvc.Models;

it seems fixed

![image](https://user-images.githubusercontent.com/19665289/135570484-b2ff6d6f-7a1a-446e-8cad-099a92382f89.png)
