### ISSUE TITLE
Data structure: Re-assign an existing data structure to a new created dataset with a new data structure

### ISSUE THREAD

**Issue by alsayedal** [BEXIS2/Core#772]
**Is your feature request related to a problem? Please describe.**
Sometimes, it happens to create a new dataset with a new data structure, fill metadata, and after a while, you need to define data structure and upload primary data. But there is an existing data structure that could be reused 

**Describe the solution you'd like**
Allow the possibility to copy the existing data structure to the new one instead of going to define the data structure a variable by a variable.

**Describe alternatives you've considered**

**Additional context**

**Comment by geofranzi** [comment]
part of #847
