### ISSUE TITLE
Missing value disappears after clicking on the save

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#774]
**Describe the bug**
Sometimes, when I create a data structure, the missing value disappears for some variables after clicking on the save button. 
Sometimes the missing value definition is totally gone, like the screenshot.

**Screenshots**
![missing value](https://user-images.githubusercontent.com/20185586/121646565-bf19a980-ca95-11eb-9718-c7ed09360145.PNG)

**BEXIS2.14.3**
 - Browser: Google Chrome

**Comment by navabpourn** [comment]
I have always this problem with variables that I create for weight. unit=g, data type=decimal

**Comment by geofranzi** [comment]
Is it related to the use of "[ ]" ?

**Comment by navabpourn** [comment]
No, almost all of our variables have "[ ]".
Could it relate to the data type? I created two other variable templates with the same properties, only data types are different. The one with decimal type causes the same problem, but the other one with double type works normally.
