### ISSUE TITLE
Settings API

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#776]
- [x] collect which modules are active
- [x] Return a settings file for all module as JSON
- [x] Save changed settings (convert back to xml)

Implementation as one central Core function

 - [x] support als static setting files (e. g. Web.conf)

### Settings Controller
- [x] Create a Model for the Settings
- [x] Load Json
- [x] Save Json
-
### Create Json Settings file
- [x] Shell
- [x] Bam
- [x] Dcm
- [x] Dmm
- [x] Dim
- [x] MMM
- [x] Rpm
- [x] Sam
- [x] Vim

### Update Project Build Command
- [x] Shell
- [x] Bam
- [x] Dcm
- [x] Dmm
- [x] Dim
- [x] MMM
- [x] Rpm
- [x] Sam
- [x] Vim

### remove xml settings
- [x] Shell
- [x] Bam
- [x] Dcm
- [x] Dmm
- [ ] Dim
- [x] MMM
- [x] Rpm
- [x] Sam
- [x] Vim

## Vaiona
- [x] change xml to json
- [x] Module should be valid without xml but json settings 

## Settings
- [x] Place Settings entry in menu

## web.config
- [x] #884

**Comment by DavidBlaa** [comment]
the ui module is built so that entries are used as attributes and not the attributes themselves

```

<node id="dcm" /> 

<node>
  <id>dcm</id>
</node>
```

i also play with the idea to remove the xml from the backend
more work but then the use later is easier

**Comment by sventhiel** [comment]
At least within DIM for DOI, the settings in XML still exists and one open issue is to transform the structure of DOI XML settings properly into JSON.

**Comment by DavidBlaa** [comment]
it will happen every merge that may something in the old settings is added.
thats why this issues was created : https://github.com/BEXIS2/Core/issues/999

i closed that issues because it was done at before
