### ISSUE TITLE
Remove data policy checkbox from Registration page

### ISSUE THREAD

**Issue by aostrow** [BEXIS2/Core#784]
I got the following Information from the Rechtsamt of the FSU:

`die privacy policy ist eine reine Pflichtinformation. Ihr muss nicht zugestimmt werden und sie muss auch nicht akzeptiert werden. Daher bitte nur eine Checkbox für die Terms, aber nicht für die privacy policy.`

**Comment by DavidBlaa** [comment]
that sounds great.
We will definitely include that in the next release :D
