### ISSUE TITLE
BAM UI Issues

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#79]
- [x] Clicking on the column titles changes the distance between view, edit and delete icons :dagger: 
- [x] The function buttons in the party Grid need more space
![image](https://user-images.githubusercontent.com/19665289/44576710-8c408280-a78f-11e8-9695-127102d1fdab.png)

**Comment by matparsa** [comment]
issue is solved

**Comment by DavidBlaa** [comment]
- [ ] the function buttons need more space

![image](https://user-images.githubusercontent.com/19665289/44576633-57ccc680-a78f-11e8-98d2-36709a30f871.png)
