### ISSUE TITLE
Make datastructure editable

### ISSUE THREAD

**Issue by aostrow** [BEXIS2/Core#790]
Some parts of the data structure should be editable, also if it is already used.
- edit Description
- change Unit
- add Missing Value

Currently, we need to create a new data structure and re-assign it in the DB, every time changes are needed.

**Comment by geofranzi** [comment]
- the description is already editable
- add missing values would require reimport -> so it is not possible to change later
- change unit could be possible

**Comment by aostrow** [comment]
Description ist not editable. You can add something but it won't be saved.

**Comment by aostrow** [comment]
but see #791
