### ISSUE TITLE
Reformat RPM settings

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#802]
to allow editing via UI it is necessary to have a common XML structure. Please reformat into the following structure:

```XML
// without childs
 <entry key="key" value="value" type="String" description=""/>

// with childs
<entry key="keys" value="value" type="String" description="">
  <entry key="key" value="value" type="String"/>
  <entry key="key" value="value" type="String"/>
</entry>
```

current commit location (1.9.2021): dev

**Comment by MaJoHo** [comment]
Is there an good and easy way to get entry by key and even there children by key and to get there values?

**Comment by geofranzi** [comment]
solved within https://github.com/BEXIS2/Core/issues/801
