### ISSUE TITLE
Maximum of 100 variables inside a data structure

### ISSUE THREAD

**Issue by sventhiel** [BEXIS2/Core#803]
**Describe the bug**
In general, the user(s) are able to collect as many variables inside a data structure as they like. Unfortunately, there seems to be a invisible limit of 100 variables. If a user adds more, the data structure is not saved anymore. It is going to be in its previous state.

**To Reproduce**
1. Go to '/rpm/DataStructureEdit?dataStructureId=x' // with x = integer for a valid data structure id
2. Pick as many variable templates as you like and add them to the data structure. Only requirement is, that the total amount of variables exceeds 100.
3. Save the data structure by clicking on 'Save'.
4. The state of the data structure won't change. It will contain as many variables as it had before.

**Expected behavior**
Like the system works for any data structure that contains less than 100 variables, it should treat those with more than 100 similarly.

**Actual behavior**
It is not possible to create/maintain/edit data structures with more than 100 variables.

**Additional context**
After some external tests via Postman, I got that error message: "The JSON request was too large to be deserialized.". So, the content/data of a data structure with more than 100 variables exceeds the maximum default limit for a valid JSON request. Based on suggestions like [HERE](https://stackoverflow.com/a/10969382), it is possible to fix that issue.

**Comment by DavidBlaa** [comment]
thanks for the search. it worked well.
10 members are generated per variable.

With a value of 1000, only 100 variables could be created.
I added the value in the web.config.sample and gave a default value of 120000.

If we work with svelte we will push more data back and forth anyway.
