### ISSUE TITLE
Increase default execution time for SQL statements (Error during upload / create MV / sync - could not execute query)

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#816]
Currently, the default (and not visible) maximal execution time for SQL statements is **60 seconds**. This can be too short e.g. for bigger datasets. 

![image](https://user-images.githubusercontent.com/15946467/136931940-fa26de85-5d08-487e-9817-f9d2e82eb9cf.png)

The error is related to a control function, which counts the number of rows in the datatuples table and compares it with the number of rows in the materialized view. 

The count statement for 5 Mio rows currently takes **67sec** in BE. 

- [x] increase default max execution time
- [x] add to workspace

**Comment by DavidBlaa** [comment]
is changed in workspace repo
