### ISSUE TITLE
Attachments have no effect on the dataset version

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#83]
From Issue #32 

**Describe the bug**
When a dataset is changed, a new version is also created. If you look at a Dataset at Show Data, you can look at a specific version. Based on the version, the attachments should also be displayed.

**To Reproduce**
1. Create a dataset (v1)
2. Attach a file (v2)
3. call action -> .../ddm/data/showdata/1?version=1

**Expected behavior**
In version 1 the attachments are empty

**Screenshots**
![image](https://user-images.githubusercontent.com/19665289/42556390-bd7c9a1c-84eb-11e8-89b4-e3b5f55e0736.png)

**Comment by DavidBlaa** [comment]
- still not working well

e.g. 
1. i create a dataset -> v1
2. i attach 2 files -> v2
3. attach one more file -> v3

v1
![image](https://user-images.githubusercontent.com/19665289/43199718-37b7270c-9013-11e8-87a7-6ee733847f2c.png)

v2
![image](https://user-images.githubusercontent.com/19665289/43199809-7f6d135e-9013-11e8-91cc-31beebaf8495.png)

**Comment by matparsa** [comment]
it has been fixed

**Comment by DavidBlaa** [comment]
available in r2.12 rc3

**Comment by navabpourn** [comment]
It works fine in RC3. Thanks :)
