### ISSUE TITLE
New Svelte UI component for upload (single, multiple file)

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#845]
- [x] search for possible existing libs (Svelte)

implementation in UI repo:
- [ ] move issues to ui repo and link here
- [ ] single file upload + description
- [x] multiple file upload + description
- [ ] add settings to control allowed number and/or size , allowed file types, ...

**Comment by gdeioannes** [comment]
Interesting drop zone functionality
https://svelte-file-dropzone.netlify.app/?path=/story/examples--basic-dropzone

**Comment by gdeioannes** [comment]
The Drop Zone component has all the requested functionalities.
One and Multiple, Files, files types, sizes

-Looking the best way to extend the description into the component.

*Not sure if there is a separate task for the interface to set the constrains for the File upload system

**Comment by DavidBlaa** [comment]
thanks for the link, the libary works quite well. 
I have already done the first implementations. 
commits are to the task https://github.com/BEXIS2/Core/issues/818

**Comment by DavidBlaa** [comment]
i am in the process of writing a fileupload component for the svelte-core-ui, which can then be defined with settings to use the components later with the attachments as well

**Comment by geofranzi** [comment]
done within #818
