### ISSUE TITLE
Download as CSV: Add comma as separator

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#858]
The current default is "semicolon", which seems to be confusing for English Excel.

To allow both the solution would be:
![image](https://user-images.githubusercontent.com/15946467/142985775-710afa21-06a0-451c-a177-8c574648d516.png)

**Comment by geofranzi** [comment]
Problem 1: UI works only with file extensions -> it is not foreseen to add versions of it: manually solved
Problem 2: Excel throws more errors because the content does not fit the file type. It si possible (additional lib) to add the correct content type, but this even throws more errors.  ..

**Comment by DavidBlaa** [comment]
![image](https://user-images.githubusercontent.com/19665289/186350725-62c9252a-4128-4015-ba9a-7cb416e61201.png)

csv = comma
tsv = tab
txt = semicolon
