### ISSUE TITLE
email service - locking file/attachment access

### ISSUE THREAD

**Issue by sventhiel** [BEXIS2/Core#859]
tbd

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actual happens instead of the expected behavior.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by geofranzi** [comment]
@sventhiel  @DavidBlaa  is this done here?
