### ISSUE TITLE
create a location and manager to easily cache required data from the update dataset workflow for a version.

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#861]
- [x] list of the required values in miro
- [x] Create a C# class
- [x] Create a manager that stores json, reads and edits the info

~~_When upload is done - remove that file from dataset folder (do not delete because of result messages and provenance)_~~

https://miro.com/app/board/o9J_lfsbYyk=/?moveToWidget=3458764514438284054&cot=14

**Comment by geofranzi** [comment]
>  When upload is done - remove that file from dataset folder

or keep it for provenace reasons?
