### ISSUE TITLE
Create metadata structure: spelling mistake

### ISSUE THREAD

**Issue by EleonoraPetzold** [BEXIS2/Core#868]
![image](https://user-images.githubusercontent.com/42029171/146376608-1ad290b5-1c5e-45e2-a388-c8a5d6eb65dd.png)

Maybe the text can be deleted because it is written in the explanation anyhow.  
 (reporter by Cornelia)

**Comment by geofranzi** [comment]
https://netspeak.org/#q=%5Ba+an%5D+xsd
I will change the "a XSD" in "an XSD"
