### ISSUE TITLE
Refactor Import Data

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#87]
- [x] remove the data orientation selection step (Sheet structure)
- [x] make sure the step of metadata structure selection is still there (not there in iDiv version)

- [x] keep the variable name from the file as a variable name in the system (first column, no editing); see iDiv version
- [x] remove the unit and data type in the name of the variable
- [x] make all dropdowns connected and apply filtering depending on the selection
- [x] in the dropdown of the attributes: show recommendations (3-5) at the top, visually separated from the rest; show all other attributes afterwards sorted by A-Z
- [x] on top of the grid add a the idea of the guiding sentence: The variable [Name] is of [datatype], has [Unit] and means [Attribute].
- [x] each dropdown needs an entry "none" or "unknown" or "no match found" at the bottom of the list; selecting this will create a new variable that has no match of an existing attribute
- [x] descriptions should be show as a tooltip of the selected unit/datatype/attribute : posponed
- [x] add the source of attribute to the name (e.g. DWC:...) : posponed
- [ ] if possible, the datatype should be extracted from excel

**Comment by navabpourn** [comment]
- [x] remove the data orientation selection step (Sheet structure)
- [ ] make sure the step of metadata structure selection is still there (not there in iDiv version)

- [ ] keep the variable name from the file as a variable name in the system (first column, no editing); see iDiv version
- [x] remove the unit and data type in the name of the variable
- [x] make all dropdowns connected and apply filtering depending on the selection
- [x] in the dropdown of the attributes: show recommendations (3-5) at the top, visually separated from the rest; show all other attributes afterwards sorted by A-Z
- [ ] on top of the grid add a the idea of the guiding sentence: The variable [Name] is of [datatype], has [Unit] and means [Attribute].
- [ ] each dropdown needs an entry "none" or "unknown" or "no match found" at the bottom of the list; selecting this will create a new variable that has no match of an existing attribute
 -----> Data Type drop-down list has not this option
- [ ] descriptions should be show as a tooltip of the selected unit/datatype/attribute : posponed
-----> Units and Means have not tooltips
- [ ] add the source of attribute to the name (e.g. DWC:...) : posponed
- [ ] if possible, the datatype should be extracted from excel
