### ISSUE TITLE
External Login

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#882]
- [x] allow login from extern (return token)
- [x] add seed data
- [x] add to update script
- [x] allow public access

**Comment by geofranzi** [comment]
https://github.com/BEXIS2/Core/commit/8e29781e4bb284d672b7189d9d02219d4e432b35
https://github.com/BEXIS2/Core/commit/aa7c6492ca683ef34ed3fb677acece63592c83d7
https://github.com/BEXIS2/Core/commit/818aef6389012937d00a41fc9bbd587ca7173c92
https://github.com/BEXIS2/Core/commit/3b258896b4cbd3c187703ccd7129b4f35594d6e2
https://github.com/BEXIS2/Core/commit/f8c568c35d7025dbd510c02a6c75475f9b1b40ac

https://github.com/BEXIS2/Core/commit/cfd072e658fe3eafc361efe86e707855530f2ac4
https://github.com/BEXIS2/Core/commit/d86a671e9c2b24b0ce78694fafab0e8b56f6a040
https://github.com/BEXIS2/Core/commit/4599113871c205683f29578fb5cecfd3a74c96f1
https://github.com/BEXIS2/Core/commit/30c0a337d6e2f1cdd93a02957ffd2233c94af4d8
https://github.com/BEXIS2/Core/commit/2820c46c48c5f33a1774e88636202f48bbc2ec0d

**Comment by geofranzi** [comment]
Was the last task done @sventhiel  ?

**Comment by sventhiel** [comment]
Yes, I checked a clean fresh database locally, so the entry inside the database is existing without any feature. So, @geofranzi it should be publicly available.
