### ISSUE TITLE
Update DIM Seedata 

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#89]
in the parties there are added relationshiptypes like owner.

ABCD
- [x] add this releationshiptypes to the mapping in the metadata structure
- [x] map person adress & email

GBIF
- [x] map person adress & email

**Comment by DavidBlaa** [comment]
availbale in 2.12 rc3

**Comment by navabpourn** [comment]
It is not clear how to map the owner with these metadata structures.

**Comment by navabpourn** [comment]
There is not a node for email in the system.
