### ISSUE TITLE
Add parties (isMain parts) and other fields to the Dataset API needed for citation generation

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#894]
For DataCite (DOI) and the generation of a citation string, we need a function that gets the first and last name (isMain parts in the party XML) of a name. 
- [x] add party parts 
- [x] add other fields: versionName, versionPublicAccess, versionPublicAccessDate, publicationDate
- [x] add version Date
- [x] add Name split for non-found parties

**Comment by geofranzi** [comment]
add version Date
 add Name split for non-found parties

**Comment by DavidBlaa** [comment]
all mapped keys are going to the name split function.
define a list before in the code which keys are persons and only use them
