### ISSUE TITLE
Editing & Deletion of assigned Data Structure 

### ISSUE THREAD

**Issue by a5a351e7** [BEXIS2/Core#9]
If you create a data structure and assign it to a dataset, you are not able to edit or delete the data structure. It should be possible to edit or delete it if the assigned dataset(s) got no primary data.

An example case: A scientist adds his variables to a datastructure and assigns this to a dataset. During the upload process he recognizes a spelling mistake. No data have been uploaded to this point. The current way is to delete dataset and then the data structure und to recreate it.

This takes a lot of time and frustrates the user.

- [ ] design the logic of change, under what conditions, by whom, what can be changed (rename variable? display pattern?)

**Comment by geofranzi** [comment]
Without uploaded data it's now possible to change the data structure.
