### ISSUE TITLE
Ui Issue with arrows in the DIM Metadata Mapping

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#90]
**Describe the bug**
sometimes the arrows in the mapping page are connection to places that are not set as edges for the arrows.

![image](https://user-images.githubusercontent.com/19665289/42988992-d173c01c-8bfe-11e8-838d-db9265d19291.png)

**Comment by DavidBlaa** [comment]
available in r2.12 rc3

**Comment by navabpourn** [comment]
Not yet :(

**Comment by navabpourn** [comment]
I could not produce this issue in RC3 :)
