### ISSUE TITLE
Remove a mapping from a single element

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#91]
**Describe the bug**
When a complex mapping is set but not created. Then when remove a single mapping the window freeze.

**To Reproduce**
1. Add Source
2. Add Traget
3. draw a mapping from a single source element to a single target element
4. remove the single mapping

**Comment by navabpourn** [comment]
It is not done in RC2

![mapping](https://user-images.githubusercontent.com/20185586/43944170-4cf4afc8-9c7e-11e8-8aed-917f04a9a06c.png)
