### ISSUE TITLE
Download dataset fails if the dataset does not contain primary data

### ISSUE THREAD

**Issue by CFuerstenau** [BEXIS2/Core#918]
**Describe the bug**
Download of a structured dataset fails if the dataset does not contain primary data. Browser shows white page.

**To Reproduce**
1. Go to metadata of a structured dataset (dataset with data structure) but withour uploaded primary data
2. Click on '.Download dataset with Excel'
3. 
4. See error: an empty page occures using Firefox, URL shows: www.bexis.uni-jena.de/ddm/Data/DownloadZip/31272?format=application%2Fxlsx&version=8666

**Expected behavior**
The dataset would be download. Zip contains an empty file.

**Actual behavior**
No download, no error message

**Screenshots**
![grafik](https://user-images.githubusercontent.com/45873895/172586443-257d8e88-51bc-47be-ae05-1a1bf460888a.png)

**Desktop (please complete the following information):**
 - Browser: Firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by geofranzi** [comment]
https://github.com/BEXIS2/Core/issues/562

**Comment by geofranzi** [comment]
don within 2.16
