### ISSUE TITLE
DIM Settings Refactoring - DOI

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#965]
in 2.15 we added doi settings in dim.settings.xml

- [x] update json settings

**Comment by sventhiel** [comment]
So far, there was a mis-match between "dim.settings.json" within the module ui project and workspace. This happens over time, because there is no synchronization between those two files.

**Comment by sventhiel** [comment]
We need to wait for a "final" version of constraint-1274 before we can move changes related to the settings controller back to dev.

**Comment by sventhiel** [comment]
Currently, there is an error message on dev.bexis2.uni-jena.de poping up at settings page. This needs to be fixed asap.
