### ISSUE TITLE
Metadata import via API only works with metadata structure id 1

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Core#977]
### Is there an existing issue for this?

- [X] I searched for a similar issue and didn't find a suitable one.

### What is going wrong?

via API you can only update datasets that belong to metadata structure id 1.

**Comment by sventhiel** [comment]
Just as a supplimentary comment. @DavidBlaa had a closer look and found some hard coded references corresponding to use metadata structure with id=1, only. Those parts had to be replaced by considering the proper parameter which is passed into the function.
